"""Module for NationalInstruments.VeriStand.WorkspaceMacro."""

from __future__ import annotations

import clr

clr.AddReference("NationalInstruments.VeriStand.WorkspaceMacro")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.WorkspaceMacro  # type: ignore
import System  # type: ignore

from .._autogenerated_utils import *
from .. import *


@_register_dotnet_type(NationalInstruments.VeriStand.WorkspaceMacro.CommandLineInfo, False)
class CommandLineInfo(_DotNetBase):
    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def seconds(self) -> float:
        try:
            dotnet_result = self._dotnet_instance.seconds
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @seconds.setter
    def seconds(self, value: float):
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.seconds = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def cmd_line(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.cmdLine
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @cmd_line.setter
    def cmd_line(self, value: str):
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.cmdLine = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
