"""Module for NationalInstruments.VeriStand.Data."""

from __future__ import annotations

from typing import Any, Callable, overload, Sequence

import clr

clr.AddReference("NationalInstruments.VeriStand.DataTypes")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.Data  # type: ignore
import System  # type: ignore

from .._autogenerated_utils import *
from .. import *


@_register_dotnet_type(NationalInstruments.VeriStand.Data.DataResource)
class DataResource(_DotNetBase):
    """Represents a source of data for a real-time sequence."""

    @overload
    def __init__(self):
        """Initializes a new instance of niveristand.data.DataResource."""

    @overload
    def __init__(self, node: DataResource):
        """Initializes a new instance of niveristand.data.DataResource by copying an existing instance.

        Args:
            node: The instance of niveristand.data.DataResource to copy.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    def clone(self) -> Any:
        """Creates a new object that is a copy of the current data resource.

        Returns:
            Any: A new system.Object that is a copy of this instance.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.Clone(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def equals(self, other: DataResource) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.data.DataResource. This is an abstract declaration only. Derived classes must implement the correct Equals comparison for that class.

        Args:
            other: The niveristand.data.DataResource object to compare with the current instance.

        Returns:
            bool: true if other is equal to the current instance of niveristand.data.DataResource; otherwise false.
        """
        unwrapped = _unwrap(None, other)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def subscribe_property_changed_event(self, handler: Callable[[Any, Any], None]) -> None:
        """Occurs when a property value changes.

        ``handler(sender: Any, e: Any) -> None``

        sender:

        e:
        """
        shim = _subscribe_event_handler(handler, self._dotnet_instance, "PropertyChanged", System.ComponentModel.PropertyChangedEventHandler)
        self._dotnet_instance.PropertyChanged += shim

    def unsubscribe_property_changed_event(self, handler: Callable[[Any, Any], None]) -> None:
        """Pass the same callable that was given to ``subscribe_property_changed_event``."""
        shim = _pop_event_handler_from_cache(handler, self._dotnet_instance, "PropertyChanged")
        if shim is not None:
            self._dotnet_instance.PropertyChanged -= shim


@_register_dotnet_type(NationalInstruments.VeriStand.Data.DataValue)
class DataValue(DataResource):
    """Represents the value of data for a real-time sequence."""

    @overload
    def __init__(self):
        """Initializes a new instance of niveristand.data.DataValue."""

    @overload
    def __init__(self, node: DataValue):
        """Initializes a new instance of niveristand.data.DataValue by copying an existing instance.

        Args:
            node: The instance of niveristand.data.DataValue to copy.
        """

    @overload
    def __init__(self, units: str):
        """Initializes a new instance of niveristand.data.DataValue with the specified units.

        Args:
            units: The units for the data value. Units can be any string that makes sense for the data value.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def type(self) -> DataType:
        """Gets the data type of the data value."""
        try:
            dotnet_result = self._dotnet_instance.Type
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def units(self) -> str:
        """Gets or sets the units of the data value. Units can be any string that makes sense for the data value."""
        try:
            dotnet_result = self._dotnet_instance.Units
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @units.setter
    def units(self, value: str):
        """Gets or sets the units of the data value. Units can be any string that makes sense for the data value."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Units = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def size(self) -> int:
        """Gets the size of the data value."""
        try:
            dotnet_result = self._dotnet_instance.Size
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_bytes(self) -> Sequence[int]:
        """Returns the data value as an array of bytes.

        Returns:
            Sequence[int]: An array of bytes.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetBytes(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def set_bytes(self, bytes: Sequence[int]):
        """Sets the niveristand.data.DataValue based on bytes. This is an abstract declaration only. Derived classes must implement the correct SetBytes method for that class.

        Args:
            bytes: An array of bytes.
        """
        unwrapped = _unwrap(None, bytes)
        try:
            dotnet_result = self._dotnet_instance.SetBytes(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @staticmethod
    def get_data_value_of_type(type: DataType) -> DataValue:
        """Returns a niveristand.data.DataValue object with the specified data type.

        Args:
            type: The data type of the object to return, as an enumeration of niveristand.data.DataType.

        Returns:
            DataValue: The niveristand.data.DataValue object of the specified data type.
        """
        unwrapped = _unwrap(None, type)
        try:
            dotnet_result = NationalInstruments.VeriStand.Data.DataValue.GetDataValueOfType(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @staticmethod
    def to_best_int(value: str) -> DataValue:
        """Returns a niveristand.data.DataValue object representing an niveristand.data.I32Value, niveristand.data.U32Value, niveristand.data.I64Value, or niveristand.data.U64Value.

        Args:
            value: An integer representation.

        Returns:
            DataValue: A niveristand.data.DataValue object representing an niveristand.data.I32Value, niveristand.data.U32Value, niveristand.data.I64Value, or niveristand.data.U64Value.
        """
        unwrapped = _unwrap(None, value)
        try:
            dotnet_result = NationalInstruments.VeriStand.Data.DataValue.ToBestInt(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @overload
    def equals(self, other: DataResource) -> bool:
        """Returns a value indicating whether this instance is equal to the specified niveristand.data.DataResource object. This method uses niveristand.data.DataValue.type and niveristand.data.DataValue.units to determine equivalency.

        Args:
            other: The data resource to compare to this instance.

        Returns:
            bool: true if other has the same type and units as this instance; otherwise false.
        """

    @overload
    def equals(self, obj: Any) -> bool:
        """Returns a value indicating whether this instance is equal to the specified object, which must be a niveristand.data.DataValue object. This method uses Body and the CaseValue to determine equivalency.

        Args:
            obj: The niveristand.data.DataValue object to compare to this instance.

        Returns:
            bool: true if obj is equal to the current instance of niveristand.data.DataValue; otherwise false.
        """

    def equals(self, *args):
        """Returns a value indicating whether this instance is equal to the specified niveristand.data.DataResource object. This method uses niveristand.data.DataValue.type and niveristand.data.DataValue.units to determine equivalency."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Serves as a hash function for a niveristand.data.DataValue object. The hash code this method returns is suitable for use in hashing algorithms and data structures like a hash table.

        Returns:
            int: A hashcode for the current niveristand.data.DataValue object.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.Data.DataType, False)
class DataType(_DotNetEnum):
    """Specifies the data type."""

    def __init__(self, *args):
        args_len = len(args)
        if args_len in [1,2] and type(args[0]) == NationalInstruments.VeriStand.Data.DataType:
            self._dotnet_instance = args[0]
            self._py_field_name = args[1] if args_len == 2 else ""
        else:
            raise ValueError("No instance constructor for DataType")

    @_staticproperty
    def VOID() -> DataType:
        """A void or empty data type."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "Void")
        return DataType(dotnet_result, "VOID")

    @_staticproperty
    def BOOLEAN() -> DataType:
        """A Boolean."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "Boolean")
        return DataType(dotnet_result, "BOOLEAN")

    @_staticproperty
    def INT32() -> DataType:
        """A 32-bit signed integer."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "Int32")
        return DataType(dotnet_result, "INT32")

    @_staticproperty
    def UINT32() -> DataType:
        """A 32-bit unsigned integer."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "UInt32")
        return DataType(dotnet_result, "UINT32")

    @_staticproperty
    def INT64() -> DataType:
        """A 64-bit signed integer."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "Int64")
        return DataType(dotnet_result, "INT64")

    @_staticproperty
    def UINT64() -> DataType:
        """A 64-bit unsigned integer."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "UInt64")
        return DataType(dotnet_result, "UINT64")

    @_staticproperty
    def DOUBLE() -> DataType:
        """A double-precision floating point number."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "Double")
        return DataType(dotnet_result, "DOUBLE")

    @_staticproperty
    def ARRAY() -> DataType:
        """An array."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Data.DataType, "Array")
        return DataType(dotnet_result, "ARRAY")
