"""Module for NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport."""

from __future__ import annotations

from typing import overload, Sequence, Tuple

from typing_extensions import deprecated
import clr

clr.AddReference("NationalInstruments.VeriStand.SystemDefinitionAPI")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport  # type: ignore
import System  # type: ignore

from ...._autogenerated_utils import *
from ... import *
from .... import *


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.CANConfiguration)
class CANConfiguration(ICANConfiguration):
    """Represents the configuration for CAN communication."""

    @overload
    def __init__(self):
        """Parameterless constructor for CAN Configuration"""

    @overload
    def __init__(self, other: ICANConfiguration):
        """Parameterized constructor for CAN Configuration

        Args:
            other: Exported CAN Cluster Configuration
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def connect_to_real_network(self) -> bool:
        """Value indicating whether to connect to the real network."""
        try:
            dotnet_result = self._dotnet_instance.ConnectToRealNetwork
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @connect_to_real_network.setter
    def connect_to_real_network(self, value: bool):
        """Value indicating whether to connect to the real network."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.ConnectToRealNetwork = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def use_database(self) -> bool:
        """Value indicating whether to use a database."""
        try:
            dotnet_result = self._dotnet_instance.UseDatabase
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @use_database.setter
    def use_database(self, value: bool):
        """Value indicating whether to use a database."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.UseDatabase = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def database_alias(self) -> str:
        """Database alias value."""
        try:
            dotnet_result = self._dotnet_instance.DatabaseAlias
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @database_alias.setter
    def database_alias(self, value: str):
        """Database alias value."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.DatabaseAlias = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.Constants, False)
class Constants(_DotNetBase):
    """Contains constants for VirtualECU"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @_staticproperty
    def ecu_network_cluster_file_extension() -> str:
        """The default extension for ECU Network Cluster Configuration files."""
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.Constants.ECUNetworkClusterFileExtension
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.ECUNetworkClusterConfiguration)
class ECUNetworkClusterConfiguration(IECUNetworkClusterConfiguration):
    """Class for serializing and de-serializing ECU network cluster configuration."""

    @overload
    def __init__(self):
        """Parameterless constructor for cluster configuration."""

    @overload
    def __init__(self, other: IECUNetworkClusterConfiguration):
        """Parameterized constructor for cluster configuration.

        Args:
            other: Exported Ecu Cluster Configuration
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def version(self) -> str:
        """Version of the json file."""
        try:
            dotnet_result = self._dotnet_instance.Version
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @version.setter
    def version(self, value: str):
        """Version of the json file."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Version = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def database_path(self) -> str:
        """Database path."""
        try:
            dotnet_result = self._dotnet_instance.DatabasePath
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @database_path.setter
    def database_path(self, value: str):
        """Database path."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.DatabasePath = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def virtual_ecu_list(self) -> Sequence[str]:
        """Virtual ECUs that have been added to the cluster."""
        try:
            dotnet_result = self._dotnet_instance.VirtualECUList
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @virtual_ecu_list.setter
    def virtual_ecu_list(self, value: Sequence[str]):
        """Virtual ECUs that have been added to the cluster."""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', 'System.String'),))}, value)
        try:
            self._dotnet_instance.VirtualECUList = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def lin_master_model_linux_path(self) -> str:
        """LIN Master Model path."""
        try:
            dotnet_result = self._dotnet_instance.LINMasterModelLinuxPath
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @lin_master_model_linux_path.setter
    def lin_master_model_linux_path(self, value: str):
        """LIN Master Model path."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.LINMasterModelLinuxPath = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def svb_configuration(self) -> SVBConfiguration:
        """Represents the configuration for Synopsys Virtual Bus (SVB)."""
        try:
            dotnet_result = self._dotnet_instance.SVBConfiguration
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @svb_configuration.setter
    def svb_configuration(self, value: SVBConfiguration):
        """Represents the configuration for Synopsys Virtual Bus (SVB)."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.SVBConfiguration = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def serialize_to(self, cluster_configuration_file_path: str):
        """Serialize the configuration to json file.

        Args:
            cluster_configuration_file_path: ECU Network Cluster Configuration File Path.
        """
        unwrapped = _unwrap(None, cluster_configuration_file_path)
        try:
            dotnet_result = self._dotnet_instance.SerializeTo(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @staticmethod
    def try_deserialize_from(model_path: str) -> Tuple[bool, IECUNetworkClusterConfiguration]:
        """Try deserializing the niveristand.systemdefinitionapi.modelsupport.virtualecusupport.ECUNetworkClusterConfiguration from a JSON file (.nivsecunw file).

        Args:
            model_path: The path to the JSON file from which the configuration will be loaded.

        Returns:
            return_value (bool): true if the deserialization is successful.
            ecu_network_cluster_configuration (IECUNetworkClusterConfiguration): The deserialized ECU network cluster configuration.
        """
        unwrapped = _unwrap(None, model_path)
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.ECUNetworkClusterConfiguration.TryDeserializeFrom(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @staticmethod
    def deserialize_from(file_path: str) -> IECUNetworkClusterConfiguration:
        """Deserializes the niveristand.systemdefinitionapi.modelsupport.virtualecusupport.ECUNetworkClusterConfiguration from a JSON file (.nivsecunw file).

        Args:
            file_path: The path to the JSON file from which the configuration will be loaded.

        Returns:
            IECUNetworkClusterConfiguration: The deserialized ECU network cluster configuration.
        """
        unwrapped = _unwrap(None, file_path)
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.ECUNetworkClusterConfiguration.DeserializeFrom(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.EthernetConfiguration)
class EthernetConfiguration(IEthernetConfiguration):
    """Represents the configuration for Ethernet communication."""

    @overload
    def __init__(self):
        """Parameterless constructor for Ethernet Configuration"""

    @overload
    def __init__(self, other: IEthernetConfiguration):
        """Parameterized constructor for Ethernet Configuration

        Args:
            other: Exported Ethernet Cluster Configuration
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def connect_to_real_network(self) -> bool:
        """Value indicating whether to connect to the real network."""
        try:
            dotnet_result = self._dotnet_instance.ConnectToRealNetwork
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @connect_to_real_network.setter
    def connect_to_real_network(self, value: bool):
        """Value indicating whether to connect to the real network."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.ConnectToRealNetwork = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def virtual_ecumac_addresses(self) -> Sequence[str]:
        """Virtual ECU MAC Addresses."""
        try:
            dotnet_result = self._dotnet_instance.VirtualECUMACAddresses
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @virtual_ecumac_addresses.setter
    def virtual_ecumac_addresses(self, value: Sequence[str]):
        """Virtual ECU MAC Addresses."""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', 'System.String'),))}, value)
        try:
            self._dotnet_instance.VirtualECUMACAddresses = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.LINConfiguration)
class LINConfiguration(ILINConfiguration):
    """Represents the configuration for LIN communication."""

    @overload
    def __init__(self):
        """Parameterless constructor for LIN Configuration"""

    @overload
    def __init__(self, other: ILINConfiguration):
        """Parameterized constructor for LIN Configuration

        Args:
            other: Exported LIN Cluster Configuration
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def connect_to_real_network(self) -> bool:
        """Value indicating whether to connect to the real network."""
        try:
            dotnet_result = self._dotnet_instance.ConnectToRealNetwork
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @connect_to_real_network.setter
    def connect_to_real_network(self, value: bool):
        """Value indicating whether to connect to the real network."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.ConnectToRealNetwork = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def use_database(self) -> bool:
        """Value indicating whether to use a database."""
        try:
            dotnet_result = self._dotnet_instance.UseDatabase
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @use_database.setter
    def use_database(self, value: bool):
        """Value indicating whether to use a database."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.UseDatabase = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def database_alias(self) -> str:
        """Database alias value."""
        try:
            dotnet_result = self._dotnet_instance.DatabaseAlias
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @database_alias.setter
    def database_alias(self, value: str):
        """Database alias value."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.DatabaseAlias = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def virtual_tx_frame_ids(self) -> Sequence[int]:
        """Virtual transmission frame IDs."""
        try:
            dotnet_result = self._dotnet_instance.VirtualTxFrameIDs
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @virtual_tx_frame_ids.setter
    def virtual_tx_frame_ids(self, value: Sequence[int]):
        """Virtual transmission frame IDs."""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', 'System.Int32'),))}, value)
        try:
            self._dotnet_instance.VirtualTxFrameIDs = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    @deprecated('Use virtual_tx_frame_ids.')
    def virtual_tx_frame_i_ds(self) -> Sequence[int]:
        return self.virtual_tx_frame_ids

    @virtual_tx_frame_i_ds.setter
    @deprecated('Use virtual_tx_frame_ids.')
    def virtual_tx_frame_i_ds(self, value: Sequence[int]) -> None:
        self.virtual_tx_frame_ids = value


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VirtualECUSupport.SVBConfiguration)
class SVBConfiguration(_DotNetBase):
    """Represents the configuration for Synopsys Virtual Bus (SVB)."""

    @overload
    def __init__(self):
        """Parameterless constructor for SVB Configuration."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def rx_fifo_capacity(self) -> int:
        """Number of frames that can be buffered by the controller's Rx FIFO. If Rx Fifo Capacity is not set, the default capacity is either 2048 or other value set by V-ECUs."""
        try:
            dotnet_result = self._dotnet_instance.RxFifoCapacity
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @rx_fifo_capacity.setter
    def rx_fifo_capacity(self, value: int):
        """Number of frames that can be buffered by the controller's Rx FIFO. If Rx Fifo Capacity is not set, the default capacity is either 2048 or other value set by V-ECUs."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.RxFifoCapacity = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
