"""Module for NationalInstruments.VeriStand.Contracts."""

from __future__ import annotations

from typing import overload

import datetime

import clr

clr.AddReference("NationalInstruments.VeriStand.APIInterface")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.Contracts  # type: ignore
import System  # type: ignore

from .._autogenerated_utils import *
from .. import *


@_register_dotnet_type(NationalInstruments.VeriStand.Contracts.AlarmFlag, False)
class AlarmFlag(_DotNetEnum):
    def __init__(self, *args):
        args_len = len(args)
        if args_len in [1,2] and type(args[0]) == NationalInstruments.VeriStand.Contracts.AlarmFlag:
            self._dotnet_instance = args[0]
            self._py_field_name = args[1] if args_len == 2 else ""
        else:
            raise ValueError("No instance constructor for AlarmFlag")

    @_staticproperty
    def SET() -> AlarmFlag:
        dotnet_result = getattr(NationalInstruments.VeriStand.Contracts.AlarmFlag, "Set")
        return AlarmFlag(dotnet_result, "SET")

    @_staticproperty
    def ACKNOWLEDGED() -> AlarmFlag:
        dotnet_result = getattr(NationalInstruments.VeriStand.Contracts.AlarmFlag, "Acknowledged")
        return AlarmFlag(dotnet_result, "ACKNOWLEDGED")

    @_staticproperty
    def CLEARED() -> AlarmFlag:
        dotnet_result = getattr(NationalInstruments.VeriStand.Contracts.AlarmFlag, "Cleared")
        return AlarmFlag(dotnet_result, "CLEARED")

    @_staticproperty
    def ALL() -> AlarmFlag:
        """Used when all the flags have changed, for example when a target is redeployed to."""
        dotnet_result = getattr(NationalInstruments.VeriStand.Contracts.AlarmFlag, "All")
        return AlarmFlag(dotnet_result, "ALL")


@_register_dotnet_type(NationalInstruments.VeriStand.Contracts.AlarmFlagDataType)
class AlarmFlagDataType(_DotNetBase):
    """Provides data about the alarm flag."""

    @overload
    def __init__(self, is_active: bool, value: float, absolute_time: datetime.datetime):
        """Creates an instance of AlarmFlagData

        Args:
            is_active: Indicates whether the flag is active.
            value: The alarm channel value that caused a change in this flag.
            absolute_time: The absolute time when the alarm watch channel value changed.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def is_active(self) -> bool:
        try:
            dotnet_result = self._dotnet_instance.IsActive
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @is_active.setter
    def is_active(self, value: bool):
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.IsActive = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def value(self) -> float:
        try:
            dotnet_result = self._dotnet_instance.Value
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @value.setter
    def value(self, value: float):
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Value = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def absolute_time(self) -> datetime.datetime:
        try:
            dotnet_result = self._dotnet_instance.AbsoluteTime
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @absolute_time.setter
    def absolute_time(self, value: datetime.datetime):
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.AbsoluteTime = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.Contracts.RuntimeConfigurationChangeAction, False)
class RuntimeConfigurationChangeAction(_DotNetEnum):
    def __init__(self, *args):
        args_len = len(args)
        if args_len in [1,2] and type(args[0]) == NationalInstruments.VeriStand.Contracts.RuntimeConfigurationChangeAction:
            self._dotnet_instance = args[0]
            self._py_field_name = args[1] if args_len == 2 else ""
        else:
            raise ValueError("No instance constructor for RuntimeConfigurationChangeAction")

    @_staticproperty
    def APPLIED() -> RuntimeConfigurationChangeAction:
        dotnet_result = getattr(NationalInstruments.VeriStand.Contracts.RuntimeConfigurationChangeAction, "Applied")
        return RuntimeConfigurationChangeAction(dotnet_result, "APPLIED")

    @_staticproperty
    def REMOVED() -> RuntimeConfigurationChangeAction:
        dotnet_result = getattr(NationalInstruments.VeriStand.Contracts.RuntimeConfigurationChangeAction, "Removed")
        return RuntimeConfigurationChangeAction(dotnet_result, "REMOVED")

    @_staticproperty
    def ERROR() -> RuntimeConfigurationChangeAction:
        dotnet_result = getattr(NationalInstruments.VeriStand.Contracts.RuntimeConfigurationChangeAction, "Error")
        return RuntimeConfigurationChangeAction(dotnet_result, "ERROR")
