"""Module for NationalInstruments.VeriStand.CustomDevice."""

from __future__ import annotations

import clr

clr.AddReference("NationalInstruments.VeriStand.XMLReader")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.CustomDevice  # type: ignore
import System  # type: ignore

from .._autogenerated_utils import *
from .. import *


@_register_dotnet_type(NationalInstruments.VeriStand.CustomDevice.PathType, False)
class PathType(_DotNetEnum):
    def __init__(self, *args):
        args_len = len(args)
        if args_len in [1,2] and type(args[0]) == NationalInstruments.VeriStand.CustomDevice.PathType:
            self._dotnet_instance = args[0]
            self._py_field_name = args[1] if args_len == 2 else ""
        else:
            raise ValueError("No instance constructor for PathType")

    @_staticproperty
    def ABSOLUTE() -> PathType:
        dotnet_result = getattr(NationalInstruments.VeriStand.CustomDevice.PathType, "Absolute")
        return PathType(dotnet_result, "ABSOLUTE")

    @_staticproperty
    def TO_BASE() -> PathType:
        dotnet_result = getattr(NationalInstruments.VeriStand.CustomDevice.PathType, "ToBase")
        return PathType(dotnet_result, "TO_BASE")

    @_staticproperty
    def TO_COMMON_DOC_DIR() -> PathType:
        dotnet_result = getattr(NationalInstruments.VeriStand.CustomDevice.PathType, "ToCommonDocDir")
        return PathType(dotnet_result, "TO_COMMON_DOC_DIR")

    @_staticproperty
    def TO_APPLICATION_DATA_DIR() -> PathType:
        dotnet_result = getattr(NationalInstruments.VeriStand.CustomDevice.PathType, "ToApplicationDataDir")
        return PathType(dotnet_result, "TO_APPLICATION_DATA_DIR")
