"""Module for NationalInstruments.VeriStand."""

from __future__ import annotations

from typing import Any, overload, Sequence

import clr

clr.AddReference("NationalInstruments.VeriStand")
import NationalInstruments.VeriStand  # type: ignore
import System  # type: ignore

from ._autogenerated_utils import *


@_register_dotnet_type(NationalInstruments.VeriStand.Error)
class VeriStandSdfError(Exception):
    """Represents NI VeriStand error information, including an integer error code and a string error message. Error objects are immutable once created."""

    def __str__(self) -> str:
        # Only use resolved_error_message if necessary; it often returns
        # "Additional error information is not available" before the error
        message = self.message if self.message else self.resolved_error_message
        return f"{int(self.error_code)} ({str(self._dotnet_instance)}): {message}"

    @overload
    def __init__(self, code: int, message: str):
        """Initializes a new instance of niveristand.Error with the specified integer error code and error message.

        Args:
            code: The integer error code with which to initialize niveristand.Error.
            message: The error message for the niveristand.Error.
        """

    @overload
    def __init__(self, code: ErrorCode, message: str):
        """Initializes a new instance of niveristand.Error with the specified error code and error message. The error code must be contained in the niveristand.ErrorCode enumeration.

        Args:
            code: The niveristand.ErrorCode with which to initialize niveristand.Error.
            message: The error message of the niveristand.Error.
        """

    @overload
    def __init__(self, code: int, message: str, resolved_error: str):
        """Initializes a new instance of niveristand.Error with the specified integer error code, error message, and resolved error information.

        Args:
            code: The integer error code with which to initialize niveristand.Error.
            message: The error message for the niveristand.Error.
            resolved_error: The resolved error information for the niveristand.Error.
        """

    @overload
    def __init__(self, code: ErrorCode, message: str, resolved_error: str):
        """Initializes a new instance of niveristand.Error with the specified error code, error message, and resolved error information. The error code must be contained in the niveristand.ErrorCode enumeration.

        Args:
            code: The niveristand.ErrorCode with which to initialize niveristand.Error.
            message: The error message for the niveristand.Error.
            resolved_error: The resolved error information for the niveristand.Error.
        """

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.Error class."""

    @overload
    def __init__(self, code: int):
        """Initializes a new instance of niveristand.Error with the specified integer error code.

        Args:
            code: The integer error code with which to initialize niveristand.Error.
        """

    @overload
    def __init__(self, code: ErrorCode):
        """Initializes a new instance of niveristand.Error with the specified error code. The error code must be contained in the niveristand.ErrorCode enumeration.

        Args:
            code: The niveristand.ErrorCode with which to initialize niveristand.Error.
        """

    @overload
    def __init__(self, e: System.Exception):
        """Initializes a new instance of niveristand.Error using the data in an exception.

        Args:
            e: The exception with which to initialize a new niveristand.Error object.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def code(self) -> int:
        """Gets the error code for the current instance of niveristand.Error and returns it as an integer."""
        try:
            dotnet_result = self._dotnet_instance.Code
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def message(self) -> str:
        """Gets the error message and returns it as a string."""
        try:
            dotnet_result = self._dotnet_instance.Message
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def is_error(self) -> bool:
        """Gets a Boolean value indicating whether the niveristand.Error object contains an error state."""
        try:
            dotnet_result = self._dotnet_instance.IsError
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def resolved_error_message(self) -> str:
        """Gets the resolved error message. The resolved error message provides error information for non-LabVIEW applications."""
        try:
            dotnet_result = self._dotnet_instance.ResolvedErrorMessage
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def is_defined_error_code(self) -> bool:
        """Gets a Boolean value indicating whether or not the integer error code is defined in the niveristand.ErrorCode enumeration."""
        try:
            dotnet_result = self._dotnet_instance.IsDefinedErrorCode
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def error_code(self) -> ErrorCode:
        """Gets the niveristand.ErrorCode enumeration for the current niveristand.Error. If the integer error code is not defined in niveristand.ErrorCode, returns the UnexpectedError enumeration."""
        try:
            dotnet_result = self._dotnet_instance.ErrorCode
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_string(self) -> str:
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToString(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def __or__(self, other):
        if isinstance(other, _DotNetBase):
            return _wrap(self._dotnet_instance | other._dotnet_instance)
        return NotImplemented

@_register_dotnet_type(NationalInstruments.VeriStand.Error)
class VeriStandError(_DotNetBase):
    """Represents NI VeriStand error information, including an integer error code and a string error message. Error objects are immutable once created."""

    def __str__(self) -> str:
        # Only use resolved_error_message if necessary; it often returns
        # "Additional error information is not available" before the error
        message = self.message if self.message else self.resolved_error_message
        return f"{int(self.error_code)} ({str(self._dotnet_instance)}): {message}"

    @overload
    def __init__(self, code: int, message: str):
        """Initializes a new instance of niveristand.Error with the specified integer error code and error message.

        Args:
            code: The integer error code with which to initialize niveristand.Error.
            message: The error message for the niveristand.Error.
        """

    @overload
    def __init__(self, code: ErrorCode, message: str):
        """Initializes a new instance of niveristand.Error with the specified error code and error message. The error code must be contained in the niveristand.ErrorCode enumeration.

        Args:
            code: The niveristand.ErrorCode with which to initialize niveristand.Error.
            message: The error message of the niveristand.Error.
        """

    @overload
    def __init__(self, code: int, message: str, resolved_error: str):
        """Initializes a new instance of niveristand.Error with the specified integer error code, error message, and resolved error information.

        Args:
            code: The integer error code with which to initialize niveristand.Error.
            message: The error message for the niveristand.Error.
            resolved_error: The resolved error information for the niveristand.Error.
        """

    @overload
    def __init__(self, code: ErrorCode, message: str, resolved_error: str):
        """Initializes a new instance of niveristand.Error with the specified error code, error message, and resolved error information. The error code must be contained in the niveristand.ErrorCode enumeration.

        Args:
            code: The niveristand.ErrorCode with which to initialize niveristand.Error.
            message: The error message for the niveristand.Error.
            resolved_error: The resolved error information for the niveristand.Error.
        """

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.Error class."""

    @overload
    def __init__(self, code: int):
        """Initializes a new instance of niveristand.Error with the specified integer error code.

        Args:
            code: The integer error code with which to initialize niveristand.Error.
        """

    @overload
    def __init__(self, code: ErrorCode):
        """Initializes a new instance of niveristand.Error with the specified error code. The error code must be contained in the niveristand.ErrorCode enumeration.

        Args:
            code: The niveristand.ErrorCode with which to initialize niveristand.Error.
        """

    @overload
    def __init__(self, e: System.Exception):
        """Initializes a new instance of niveristand.Error using the data in an exception.

        Args:
            e: The exception with which to initialize a new niveristand.Error object.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def code(self) -> int:
        """Gets the error code for the current instance of niveristand.Error and returns it as an integer."""
        try:
            dotnet_result = self._dotnet_instance.Code
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def message(self) -> str:
        """Gets the error message and returns it as a string."""
        try:
            dotnet_result = self._dotnet_instance.Message
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def is_error(self) -> bool:
        """Gets a Boolean value indicating whether the niveristand.Error object contains an error state."""
        try:
            dotnet_result = self._dotnet_instance.IsError
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def resolved_error_message(self) -> str:
        """Gets the resolved error message. The resolved error message provides error information for non-LabVIEW applications."""
        try:
            dotnet_result = self._dotnet_instance.ResolvedErrorMessage
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def is_defined_error_code(self) -> bool:
        """Gets a Boolean value indicating whether or not the integer error code is defined in the niveristand.ErrorCode enumeration."""
        try:
            dotnet_result = self._dotnet_instance.IsDefinedErrorCode
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def error_code(self) -> ErrorCode:
        """Gets the niveristand.ErrorCode enumeration for the current niveristand.Error. If the integer error code is not defined in niveristand.ErrorCode, returns the UnexpectedError enumeration."""
        try:
            dotnet_result = self._dotnet_instance.ErrorCode
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_string(self) -> str:
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToString(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def __or__(self, other):
        if isinstance(other, _DotNetBase):
            return _wrap(self._dotnet_instance | other._dotnet_instance)
        return NotImplemented


@_register_dotnet_type(NationalInstruments.VeriStand.ErrorCode, False)
class ErrorCode(_DotNetEnum):
    """Defines the types of error codes that NI VeriStand can return."""

    def __init__(self, *args):
        args_len = len(args)
        if args_len in [1,2] and type(args[0]) == NationalInstruments.VeriStand.ErrorCode:
            self._dotnet_instance = args[0]
            self._py_field_name = args[1] if args_len == 2 else ""
        else:
            raise ValueError("No instance constructor for ErrorCode")

    @_staticproperty
    def SUCCESS() -> ErrorCode:
        """No error."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "Success")
        return ErrorCode(dotnet_result, "SUCCESS")

    @_staticproperty
    def LAB_VIEW_MATHEMATICS_VI_BRACKET_PROBLEM() -> ErrorCode:
        """Bracket problem"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "LabVIEWMathematicsVIBracketProblem")
        return ErrorCode(dotnet_result, "LAB_VIEW_MATHEMATICS_VI_BRACKET_PROBLEM")

    @_staticproperty
    def LAB_VIEW_MATHEMATICS_VI_BEGINNING_BRACKET_PROBLEM() -> ErrorCode:
        """Bracket problem at the beginning"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "LabVIEWMathematicsVIBeginningBracketProblem")
        return ErrorCode(dotnet_result, "LAB_VIEW_MATHEMATICS_VI_BEGINNING_BRACKET_PROBLEM")

    @_staticproperty
    def LAB_VIEW_MATHEMATICS_VI_END_BRACKET_PROBLEM() -> ErrorCode:
        """Bracket problem at the end"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "LabVIEWMathematicsVIEndBracketProblem")
        return ErrorCode(dotnet_result, "LAB_VIEW_MATHEMATICS_VI_END_BRACKET_PROBLEM")

    @_staticproperty
    def FILE_VERSION_UNSUPPORTED() -> ErrorCode:
        """NI VeriStand was unable to mutate the workspace file to the current version. NI VeriStand error: -307525"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "FileVersionUnsupported")
        return ErrorCode(dotnet_result, "FILE_VERSION_UNSUPPORTED")

    @_staticproperty
    def SERVICE_CONFIGURATION_FILE() -> ErrorCode:
        """Failed to read the NI VeriStand Service configuration file. Please repair your NI VeriStand installation to resolve this issue. NI VeriStand error: -307681"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ServiceConfigurationFile")
        return ErrorCode(dotnet_result, "SERVICE_CONFIGURATION_FILE")

    @_staticproperty
    def UNEXPECTED_ERROR() -> ErrorCode:
        """An unexpected error has occurred in the NI VeriStand API. NI VeriStand error: -307650"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "UnexpectedError")
        return ErrorCode(dotnet_result, "UNEXPECTED_ERROR")

    @_staticproperty
    def FUNCTION_NOT_SUPPORTED() -> ErrorCode:
        """The NI VeriStand API does not support this function. NI VeriStand error: -307651"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "FunctionNotSupported")
        return ErrorCode(dotnet_result, "FUNCTION_NOT_SUPPORTED")

    @_staticproperty
    def FAILED_SERVER_CONNECTION() -> ErrorCode:
        """Failed to open a connection to VeriStand Server process NI VeriStand error: -307652"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "FailedServerConnection")
        return ErrorCode(dotnet_result, "FAILED_SERVER_CONNECTION")

    @_staticproperty
    def INVALID_FILE() -> ErrorCode:
        """Specified file is invalid or does not exist. NI VeriStand error: -307653"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InvalidFile")
        return ErrorCode(dotnet_result, "INVALID_FILE")

    @_staticproperty
    def NOT_DEPLOYED() -> ErrorCode:
        """Invalid request. NI VeriStand is not running a system definition file. NI VeriStand error: -307654"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NotDeployed")
        return ErrorCode(dotnet_result, "NOT_DEPLOYED")

    @_staticproperty
    def COMPONENT_NOT_AVAILABLE() -> ErrorCode:
        """Invalid request. NI VeriStand is missing an engine component that is required to process the request. NI VeriStand error: -307655"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ComponentNotAvailable")
        return ErrorCode(dotnet_result, "COMPONENT_NOT_AVAILABLE")

    @_staticproperty
    def NO_SYSTEM_DEFINITION_LOADED() -> ErrorCode:
        """Invalid request. NI VeriStand does not have a system definition file loaded. NI VeriStand error: -307656"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NoSystemDefinitionLoaded")
        return ErrorCode(dotnet_result, "NO_SYSTEM_DEFINITION_LOADED")

    @_staticproperty
    def INVALID_CONFIGURATION_PASSWORD() -> ErrorCode:
        """The specified password does not match the current deployed configuration password. NI VeriStand error: -307657"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InvalidConfigurationPassword")
        return ErrorCode(dotnet_result, "INVALID_CONFIGURATION_PASSWORD")

    @_staticproperty
    def HOST_RUNNING_DIFFERENT_SYSTEM_DEFINITION() -> ErrorCode:
        """The execution host is running a different system definition file than the file specified. You must deploy the system definition file in order to connect to the execution host. NI VeriStand error: -307671"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "HostRunningDifferentSystemDefinition")
        return ErrorCode(dotnet_result, "HOST_RUNNING_DIFFERENT_SYSTEM_DEFINITION")

    @_staticproperty
    def SYSTEM_DEFINITION_ALREADY_ACTIVE() -> ErrorCode:
        """NI VeriStand is unable to run the system definition file when a system definition file already is running. NI VeriStand error: -307658"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SystemDefinitionAlreadyActive")
        return ErrorCode(dotnet_result, "SYSTEM_DEFINITION_ALREADY_ACTIVE")

    @_staticproperty
    def EMPTY_PASSWORD() -> ErrorCode:
        """Invalid password input parameter. The password cannot be an empty string. NI VeriStand error: -307659"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "EmptyPassword")
        return ErrorCode(dotnet_result, "EMPTY_PASSWORD")

    @_staticproperty
    def SYSTEM_DEFINITION_DEPLOYMENT_TIMEOUT() -> ErrorCode:
        """Timeout occurred while deploying a new system definition file. NI VeriStand error: -307660"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SystemDefinitionDeploymentTimeout")
        return ErrorCode(dotnet_result, "SYSTEM_DEFINITION_DEPLOYMENT_TIMEOUT")

    @_staticproperty
    def SYSTEM_DEFINITION_DEPLOYMENT_FAILURE() -> ErrorCode:
        """NI VeriStand failed to deploy the system definition file. NI VeriStand error: -307661"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SystemDefinitionDeploymentFailure")
        return ErrorCode(dotnet_result, "SYSTEM_DEFINITION_DEPLOYMENT_FAILURE")

    @_staticproperty
    def NODE_NOT_FOUND() -> ErrorCode:
        """Node is not found in the system. NI VeriStand error: -307662"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NodeNotFound")
        return ErrorCode(dotnet_result, "NODE_NOT_FOUND")

    @_staticproperty
    def TIMEOUT() -> ErrorCode:
        """Timeout in processing request. NI VeriStand error: -307663"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "Timeout")
        return ErrorCode(dotnet_result, "TIMEOUT")

    @_staticproperty
    def CHANNEL_NOT_READABLE() -> ErrorCode:
        """Channel does not have read access. NI VeriStand error: -307664"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelNotReadable")
        return ErrorCode(dotnet_result, "CHANNEL_NOT_READABLE")

    @_staticproperty
    def CHANNEL_NOT_WRITABLE() -> ErrorCode:
        """Channel does not have write access. NI VeriStand error: -307665"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelNotWritable")
        return ErrorCode(dotnet_result, "CHANNEL_NOT_WRITABLE")

    @_staticproperty
    def CHANNEL_CANNOT_BE_FAULTED() -> ErrorCode:
        """The specified channel cannot be faulted. NI VeriStand error: -307666"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelCannotBeFaulted")
        return ErrorCode(dotnet_result, "CHANNEL_CANNOT_BE_FAULTED")

    @_staticproperty
    def TARGET_INVALID() -> ErrorCode:
        """The specified target is not defined in the deployed system definition. NI VeriStand error: -307686"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "TargetInvalid")
        return ErrorCode(dotnet_result, "TARGET_INVALID")

    @_staticproperty
    def TARGET_DISABLED() -> ErrorCode:
        """The specified target is disabled in the deployed system definition. NI VeriStand error: -307689"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "TargetDisabled")
        return ErrorCode(dotnet_result, "TARGET_DISABLED")

    @_staticproperty
    def MODEL_DIMENSION_MISMATCH() -> ErrorCode:
        """Model has a different number of inports, outports, signals, and parameters than when it originally was imported or a workspace variable has been imported with different dimensions between two or more models. NI VeriStand error: -307702"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ModelDimensionMismatch")
        return ErrorCode(dotnet_result, "MODEL_DIMENSION_MISMATCH")

    @_staticproperty
    def CHANNEL_MAPPINGS_SIZE_MISMATCH() -> ErrorCode:
        """One or more channel mappings have incompatible dimensions. Matrix channels only can be mapped to matrix channels with the same dimension. NI VeriStand error: -307728"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelMappingsSizeMismatch")
        return ErrorCode(dotnet_result, "CHANNEL_MAPPINGS_SIZE_MISMATCH")

    @_staticproperty
    def NOT_A_CHANNEL() -> ErrorCode:
        """The specified item is not a channel. NI VeriStand error: -307825"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NotAChannel")
        return ErrorCode(dotnet_result, "NOT_A_CHANNEL")

    @_staticproperty
    def NOT_A_WAVEFORM() -> ErrorCode:
        """The specified item is not a waveform. NI VeriStand error: -307824"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NotAWaveform")
        return ErrorCode(dotnet_result, "NOT_A_WAVEFORM")

    @_staticproperty
    def WAVEFORM_DATA_TYPE_MISMATCH() -> ErrorCode:
        """The data type of the waveform specification must match the data type of the waveform. NI VeriStand error: -307553"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "WaveformDataTypeMismatch")
        return ErrorCode(dotnet_result, "WAVEFORM_DATA_TYPE_MISMATCH")

    @_staticproperty
    def INVALID_STREAM_CONDITION_FOR_DATA_TYPE() -> ErrorCode:
        """The specified waveform streaming condition is not support by the data type of the specified waveform. NI VeriStand error: -307554"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InvalidStreamConditionForDataType")
        return ErrorCode(dotnet_result, "INVALID_STREAM_CONDITION_FOR_DATA_TYPE")

    @_staticproperty
    def CHANNEL_NODE_REMOVED() -> ErrorCode:
        """The referenced node is no longer valid. The referenced node was removed. NI VeriStand error: -307828"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelNodeRemoved")
        return ErrorCode(dotnet_result, "CHANNEL_NODE_REMOVED")

    @_staticproperty
    def NODE_NOT_FOUND_DURING_COMPILE() -> ErrorCode:
        """The specified node cannot be found. NI VeriStand error: -307829"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NodeNotFoundDuringCompile")
        return ErrorCode(dotnet_result, "NODE_NOT_FOUND_DURING_COMPILE")

    @_staticproperty
    def CHANNEL_LENGTH_MISMATCH() -> ErrorCode:
        """The channel dimension does not match the channel default value length. NI VeriStand error: -307830"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelLengthMismatch")
        return ErrorCode(dotnet_result, "CHANNEL_LENGTH_MISMATCH")

    @_staticproperty
    def CHANNEL_NOT_SCALABLE() -> ErrorCode:
        """The specified channel cannot be scaled. NI VeriStand error: -307668"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelNotScalable")
        return ErrorCode(dotnet_result, "CHANNEL_NOT_SCALABLE")

    @_staticproperty
    def NO_PROJECT_OPEN() -> ErrorCode:
        """The specified operation cannot be completed. There is no project file currently open. NI VeriStand error: -307992"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NoProjectOpen")
        return ErrorCode(dotnet_result, "NO_PROJECT_OPEN")

    @_staticproperty
    def STIMULUS_PROFILE_SESSION_LOCKED() -> ErrorCode:
        """The specified stimulus profile session is locked. A stimulus profile session must be unlocked before any sequences in the session can be controlled. NI VeriStand error: -307980"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "StimulusProfileSessionLocked")
        return ErrorCode(dotnet_result, "STIMULUS_PROFILE_SESSION_LOCKED")

    @_staticproperty
    def SEQUENCE_NOT_FOUND_IN_SESSION() -> ErrorCode:
        """The stimulus profile session does not contain a sequence with the specified name. NI VeriStand error: -307981"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SequenceNotFoundInSession")
        return ErrorCode(dotnet_result, "SEQUENCE_NOT_FOUND_IN_SESSION")

    @_staticproperty
    def SESSION_NOT_DEPLOYED() -> ErrorCode:
        """The stimulus profile session is not deployed. NI VeriStand error: -307982"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SessionNotDeployed")
        return ErrorCode(dotnet_result, "SESSION_NOT_DEPLOYED")

    @_staticproperty
    def SESSION_ALREADY_DEPLOYED() -> ErrorCode:
        """The stimulus profile session already is deployed. NI VeriStand error: -307984"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SessionAlreadyDeployed")
        return ErrorCode(dotnet_result, "SESSION_ALREADY_DEPLOYED")

    @_staticproperty
    def RTSEQ_PARAMETER_ASSIGNMENT_PARAMETER_DOES_NOT_EXIST() -> ErrorCode:
        """The specified parameter assignment is not valid. The real-time sequence parameter does not exist."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "RtseqParameterAssignmentParameterDoesNotExist")
        return ErrorCode(dotnet_result, "RTSEQ_PARAMETER_ASSIGNMENT_PARAMETER_DOES_NOT_EXIST")

    @_staticproperty
    def BY_REFERENCE_PARAMETER_VALUE_NOT_ASSIGNED() -> ErrorCode:
        """One or more real-time sequence parameters with a by-reference evaluation was not mapped to. You must assign a value to all real-time sequence parameters that have a by-reference evaluation type."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ByReferenceParameterValueNotAssigned")
        return ErrorCode(dotnet_result, "BY_REFERENCE_PARAMETER_VALUE_NOT_ASSIGNED")

    @_staticproperty
    def SEQUENCE_COMPILE_ERROR() -> ErrorCode:
        """The specified real-time sequence contains one or more errors which caused it to fail to compile. NI VeriStand error: -307988"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SequenceCompileError")
        return ErrorCode(dotnet_result, "SEQUENCE_COMPILE_ERROR")

    @_staticproperty
    def RTSEQ_PARAMETER_ASSIGNMENT_INVALID_DATA_TYPE() -> ErrorCode:
        """A real-time sequence parameter assignment has an invalid data type. The data type of the value assigned to the parameter must match the parameter data type."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "RtseqParameterAssignmentInvalidDataType")
        return ErrorCode(dotnet_result, "RTSEQ_PARAMETER_ASSIGNMENT_INVALID_DATA_TYPE")

    @_staticproperty
    def MODEL_PARAMETER_FILE_PARSE_ERROR() -> ErrorCode:
        """Parse exception occurred in a model parameter file. NI VeriStand error: -307680"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ModelParameterFileParseError")
        return ErrorCode(dotnet_result, "MODEL_PARAMETER_FILE_PARSE_ERROR")

    @_staticproperty
    def NUMBER_OF_COEFFICIENTS_OUT_OF_RANGE() -> ErrorCode:
        """Number of coefficients for a polynomial calibration is out of range. NI VeriStand error: -307884"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NumberOfCoefficientsOutOfRange")
        return ErrorCode(dotnet_result, "NUMBER_OF_COEFFICIENTS_OUT_OF_RANGE")

    @_staticproperty
    def DUPLICATE_LOG_SESSION_NAME() -> ErrorCode:
        """A duplicate log session name was used. NI VeriStand error: -307867"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "DuplicateLogSessionName")
        return ErrorCode(dotnet_result, "DUPLICATE_LOG_SESSION_NAME")

    @_staticproperty
    def LOG_SESSION_NOT_FOUND() -> ErrorCode:
        """Log session could not be found by name. NI VeriStand error: -307865"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "LogSessionNotFound")
        return ErrorCode(dotnet_result, "LOG_SESSION_NOT_FOUND")

    @_staticproperty
    def NOT_ENOUGH_DYNAMIC_DATA_SHARING_SPACE() -> ErrorCode:
        """Unable to share data between two targets. There is not enough dynamic data sharing space. NI VeriStand error: -307738"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NotEnoughDynamicDataSharingSpace")
        return ErrorCode(dotnet_result, "NOT_ENOUGH_DYNAMIC_DATA_SHARING_SPACE")

    @_staticproperty
    def TARGET_MISSING_DATA_SHARING_DEVICE() -> ErrorCode:
        """Unable to create dynamic data sharing between targets. Either the source or destination target does not have a data sharing device. NI VeriStand error: -307737"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "TargetMissingDataSharingDevice")
        return ErrorCode(dotnet_result, "TARGET_MISSING_DATA_SHARING_DEVICE")

    @_staticproperty
    def LOG_TRIGGER_CONDITION_SYNTAX_ERROR() -> ErrorCode:
        """The specified trigger condition contains syntax errors. NI VeriStand error: -307868"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "LogTriggerConditionSyntaxError")
        return ErrorCode(dotnet_result, "LOG_TRIGGER_CONDITION_SYNTAX_ERROR")

    @_staticproperty
    def SERVER_PORT_ALREADY_IN_USE() -> ErrorCode:
        """Unable to start the NI VeriStand Server. The port address is already in use by another process. NI VeriStand error: -307684"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ServerPortAlreadyInUse")
        return ErrorCode(dotnet_result, "SERVER_PORT_ALREADY_IN_USE")

    @_staticproperty
    def NOT_AN_INLINE_CUSTOM_DEVICE() -> ErrorCode:
        """The specified item is not an inline custom device. NI VeriStand error: -307710"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NotAnInlineCustomDevice")
        return ErrorCode(dotnet_result, "NOT_AN_INLINE_CUSTOM_DEVICE")

    @_staticproperty
    def PARAMETER_NOT_FOUND() -> ErrorCode:
        """The specified parameter is not found in the system. NI VeriStand error: -307685"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ParameterNotFound")
        return ErrorCode(dotnet_result, "PARAMETER_NOT_FOUND")

    @_staticproperty
    def INVALID_DAQ_PLUGIN_FILE() -> ErrorCode:
        """A DAQ Plugin file could not be loaded. NI VeriStand error: -307526"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InvalidDaqPluginFile")
        return ErrorCode(dotnet_result, "INVALID_DAQ_PLUGIN_FILE")

    @_staticproperty
    def DUPLICATE_CHANNEL_ALIAS_MAPPINGS() -> ErrorCode:
        """A channel and the alias that references it both specify a data source mapping. A channel can only have one data source mapping. NI VeriStand error: -307711"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "DuplicateChannelAliasMappings")
        return ErrorCode(dotnet_result, "DUPLICATE_CHANNEL_ALIAS_MAPPINGS")

    @_staticproperty
    def MISMATCHED_LENGTHS() -> ErrorCode:
        """The number of channels and the number of values do not match. NI VeriStand error: -307687"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "MismatchedLengths")
        return ErrorCode(dotnet_result, "MISMATCHED_LENGTHS")

    @_staticproperty
    def INCOMPATIBLE_MODEL() -> ErrorCode:
        """The specified model is incompatible with NI VeriStand. If you are trying to deploy the model to an RT target, launch the Console Viewer tool to display the console output of the target, which includes information about the source of the error. NI VeriStand error: -307703"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "IncompatibleModel")
        return ErrorCode(dotnet_result, "INCOMPATIBLE_MODEL")

    @_staticproperty
    def UNSUPPORTED_MODEL_ARCHITECTURE() -> ErrorCode:
        """The specified model has an unsupported 32-bit architecture. NI VeriStand error: -307705"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "UnsupportedModelArchitecture")
        return ErrorCode(dotnet_result, "UNSUPPORTED_MODEL_ARCHITECTURE")

    @_staticproperty
    def UNSUPPORTED_FMU_KIND() -> ErrorCode:
        """The specified FMU was not loaded. VeriStand cannot load FMUs that do not contain a co-simulation section. NI VeriStand error: -307706"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "UnsupportedFMUKind")
        return ErrorCode(dotnet_result, "UNSUPPORTED_FMU_KIND")

    @_staticproperty
    def NON_POSITIVE_STEP_SIZE() -> ErrorCode:
        """The specified FMU was not loaded. VeriStand cannot load FMUs with a negative or zero step size. NI VeriStand error: -307707"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NonPositiveStepSize")
        return ErrorCode(dotnet_result, "NON_POSITIVE_STEP_SIZE")

    @_staticproperty
    def UNSUPPORTED_FMI_VERSION() -> ErrorCode:
        """The specified FMU is incompatible with VeriStand. Only FMI version 2.0 is compatible. NI VeriStand error: -307708"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "UnsupportedFMIVersion")
        return ErrorCode(dotnet_result, "UNSUPPORTED_FMI_VERSION")

    @_staticproperty
    def UNSUPPORTED_VS_MODEL_VERSION() -> ErrorCode:
        """This Simulink® model was compiled with an incompatible version of the VeriStand Model Generation Support toolbox. Please refer to the compatibility table and either recompile the Simulink model or upgrade your version of VeriStand. NI VeriStand error: -307709"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "UnsupportedVsModelVersion")
        return ErrorCode(dotnet_result, "UNSUPPORTED_VS_MODEL_VERSION")

    @_staticproperty
    def UNMAPPED_ALIAS() -> ErrorCode:
        """Alias is not linked to any channel. NI VeriStand error: -307617"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "UnmappedAlias")
        return ErrorCode(dotnet_result, "UNMAPPED_ALIAS")

    @_staticproperty
    def CANNOT_ADD_VS_MODEL_IN_SYSTEM_EXPLORER() -> ErrorCode:
        """You cannot use System Explorer to add a .vsmodel file to a system definition. To add a .vsmodel file, navigate to the Mapping Diagram palette and click Software &gt;&gt; Simulation Model."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "CannotAddVsModelInSystemExplorer")
        return ErrorCode(dotnet_result, "CANNOT_ADD_VS_MODEL_IN_SYSTEM_EXPLORER")

    @_staticproperty
    def CANNOT_ADD_NI_VS_ECU_NW_IN_SYSTEM_EXPLORER() -> ErrorCode:
        """You cannot use System Explorer to add a .nivsecunw file to a system definition. To add a .nivsecunw file, navigate to the Mapping Diagram palette and click Software &gt;&gt; ECU Network Cluster."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "CannotAddNiVsEcuNwInSystemExplorer")
        return ErrorCode(dotnet_result, "CANNOT_ADD_NI_VS_ECU_NW_IN_SYSTEM_EXPLORER")

    @_staticproperty
    def EMPTY_NODE_NAME() -> ErrorCode:
        """A node name cannot be an empty string."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "EmptyNodeName")
        return ErrorCode(dotnet_result, "EMPTY_NODE_NAME")

    @_staticproperty
    def NODE_ALREADY_EXISTS_BY_NAME() -> ErrorCode:
        """This node already exists in the system."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NodeAlreadyExistsByName")
        return ErrorCode(dotnet_result, "NODE_ALREADY_EXISTS_BY_NAME")

    @_staticproperty
    def INPUT_PARAMETER_INVALID() -> ErrorCode:
        """One of the input parameters to the function is invalid"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InputParameterInvalid")
        return ErrorCode(dotnet_result, "INPUT_PARAMETER_INVALID")

    @_staticproperty
    def NO_ACTION_REQUIRED() -> ErrorCode:
        """No action was required by this method; this usually indicates the method could not create a node because the node already existed."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NoActionRequired")
        return ErrorCode(dotnet_result, "NO_ACTION_REQUIRED")

    @_staticproperty
    def INCORRECT_LOG_FILE_NAME() -> ErrorCode:
        """Could not retrieve information for given log file. NI VeriStand error: -307871"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "IncorrectLogFileName")
        return ErrorCode(dotnet_result, "INCORRECT_LOG_FILE_NAME")

    @_staticproperty
    def DOWNLOAD_FILE_ERROR() -> ErrorCode:
        """There was an error downloading one or more of the requested files. NI VeriStand error: -307872"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "DownloadFileError")
        return ErrorCode(dotnet_result, "DOWNLOAD_FILE_ERROR")

    @_staticproperty
    def TARGET_DISCONNECTED() -> ErrorCode:
        """Could not complete one or more requests because a target is offline. NI VeriStand error: -307682"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "TargetDisconnected")
        return ErrorCode(dotnet_result, "TARGET_DISCONNECTED")

    @_staticproperty
    def GATEWAY_NOT_ON_LOCALHOST() -> ErrorCode:
        """Feature is supported only if the gateway is running on the localhost machine. NI VeriStand error: -307780"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "GatewayNotOnLocalhost")
        return ErrorCode(dotnet_result, "GATEWAY_NOT_ON_LOCALHOST")

    @_staticproperty
    def CHANNEL_GROUP_NOT_FOUND_IN_LOG_FILE() -> ErrorCode:
        """A channel group is missing from a log file. NI VeriStand error: -307781"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelGroupNotFoundInLogFile")
        return ErrorCode(dotnet_result, "CHANNEL_GROUP_NOT_FOUND_IN_LOG_FILE")

    @_staticproperty
    def CHANNEL_NOT_FOUND_IN_LOG_FILE() -> ErrorCode:
        """A channel is missing from a log file. NI VeriStand error: -307782"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ChannelNotFoundInLogFile")
        return ErrorCode(dotnet_result, "CHANNEL_NOT_FOUND_IN_LOG_FILE")

    @_staticproperty
    def DEPENDENCIES_CYCLE() -> ErrorCode:
        """A dependencies cycle is present in some data structure. NI VeriStand error: -307783"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "DependenciesCycle")
        return ErrorCode(dotnet_result, "DEPENDENCIES_CYCLE")

    @_staticproperty
    def STI_FILE_ERROR() -> ErrorCode:
        """STI file is not valid. NI VeriStand error: -307784"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "STIFileError")
        return ErrorCode(dotnet_result, "STI_FILE_ERROR")

    @_staticproperty
    def SLSC_CHASSIS_LOAD_FAILED() -> ErrorCode:
        """Loading the SLSC Chassis failed"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "SLSCChassisLoadFailed")
        return ErrorCode(dotnet_result, "SLSC_CHASSIS_LOAD_FAILED")

    @_staticproperty
    def ELECTRICAL_ERROR_NOT_HANDLED() -> ErrorCode:
        """There is no error provider to handle the signals of the error NI VeriStand error: -307785"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ElectricalErrorNotHandled")
        return ErrorCode(dotnet_result, "ELECTRICAL_ERROR_NOT_HANDLED")

    @_staticproperty
    def MODEL_NOT_FOUND() -> ErrorCode:
        """The requested simulation model could not be found. Navigate to the Model Configuration page in the System Explorer window and choose a different model. NI VeriStand error: -307605"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ModelNotFound")
        return ErrorCode(dotnet_result, "MODEL_NOT_FOUND")

    @_staticproperty
    def RUNTIME_CONFIGURATION_OUT_OF_SYNC() -> ErrorCode:
        """Host and target are out of sync. Please reapply the runtime configuration."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "RuntimeConfigurationOutOfSync")
        return ErrorCode(dotnet_result, "RUNTIME_CONFIGURATION_OUT_OF_SYNC")

    @_staticproperty
    def RUNTIME_CONFIGURABLE_NODE_NOT_FOUND() -> ErrorCode:
        """The requested runtime configurable node could not be found."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "RuntimeConfigurableNodeNotFound")
        return ErrorCode(dotnet_result, "RUNTIME_CONFIGURABLE_NODE_NOT_FOUND")

    @_staticproperty
    def INVALID_RUNTIME_CONFIGURABLE_NODE() -> ErrorCode:
        """The provided runtime configurable node is not valid. The node must be a RuntimeConfigurableSection node."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InvalidRuntimeConfigurableNode")
        return ErrorCode(dotnet_result, "INVALID_RUNTIME_CONFIGURABLE_NODE")

    @_staticproperty
    def RUNTIME_CONFIGURATION_SIZE_MISMATCH() -> ErrorCode:
        """The number of channels in the applied configuration exceeds the reserved channel capacity."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "RuntimeConfigurationSizeMismatch")
        return ErrorCode(dotnet_result, "RUNTIME_CONFIGURATION_SIZE_MISMATCH")

    @_staticproperty
    def INVALID_RUNTIME_CONFIGURATION_FILE() -> ErrorCode:
        """The provided runtime configuration file is not valid."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InvalidRuntimeConfigurationFile")
        return ErrorCode(dotnet_result, "INVALID_RUNTIME_CONFIGURATION_FILE")

    @_staticproperty
    def ACTION_VI_ON_RECOMPLILE_EXECUTION_FAILED() -> ErrorCode:
        """The ActionVIOnRecompile execution did not complete successfully. This could be due to exceeding the provided timeout or other issues within the Action VI. Verify the Action VI, then reapply the runtime configuration."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "ActionVIOnRecomplileExecutionFailed")
        return ErrorCode(dotnet_result, "ACTION_VI_ON_RECOMPLILE_EXECUTION_FAILED")

    @_staticproperty
    def INVALID_SIGNAL_INDEX() -> ErrorCode:
        """One or more of the specified signal indexes are not valid. Use signal indexes that are in the model."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "InvalidSignalIndex")
        return ErrorCode(dotnet_result, "INVALID_SIGNAL_INDEX")

    @_staticproperty
    def NOT_SCALAR_SIGNAL() -> ErrorCode:
        """One or more of the specified signals are not scalar. Only scalar signals can be viewed."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NotScalarSignal")
        return ErrorCode(dotnet_result, "NOT_SCALAR_SIGNAL")

    @_staticproperty
    def TARGET_RUNNING_CONNECTED_TO_A_DIFFERENT_GATEWAY() -> ErrorCode:
        """One or more of the targets in the SystemDefinition is already running, connected to another gateway. NI VeriStand error: -307673"""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "TargetRunningConnectedToADifferentGateway")
        return ErrorCode(dotnet_result, "TARGET_RUNNING_CONNECTED_TO_A_DIFFERENT_GATEWAY")

    @_staticproperty
    def NO_SPACE_TO_DEPLOY_SEQUENCE() -> ErrorCode:
        """The target does not contain enough space to deploy a new real-time (RT) sequence. You can free space by undeploying unused stimulus profile sessions that contain RT sequences."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "NoSpaceToDeploySequence")
        return ErrorCode(dotnet_result, "NO_SPACE_TO_DEPLOY_SEQUENCE")

    @_staticproperty
    def VERISTAND_AUTOMATION_EXCEPTION() -> ErrorCode:
        """Exception occurred during the VeriStand automation call."""
        dotnet_result = getattr(NationalInstruments.VeriStand.ErrorCode, "VeriStandAutomationException")
        return ErrorCode(dotnet_result, "VERISTAND_AUTOMATION_EXCEPTION")


@_register_dotnet_type(NationalInstruments.VeriStand.XMLVersionInfo)
class XMLVersionInfo(_DotNetBase):
    """Provides and configures version data for an XML file, including the major, minor, fix, and build version of the XML file."""

    @overload
    def __init__(self, major: int, minor: int, fix: int, build: int):
        """Initializes a new niveristand.XMLVersionInfo object with the specified major, minor, fix, and build data.

        Args:
            major: The major version number.
            minor: The minor version number.
            fix: The fix number.
            build: The build number.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def major(self) -> int:
        """Gets or sets the major version number for the current XML file."""
        try:
            dotnet_result = self._dotnet_instance.Major
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @major.setter
    def major(self, value: int):
        """Gets or sets the major version number for the current XML file."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Major = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def minor(self) -> int:
        """Gets or sets the minor version number for the current XML file."""
        try:
            dotnet_result = self._dotnet_instance.Minor
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @minor.setter
    def minor(self, value: int):
        """Gets or sets the minor version number for the current XML file."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Minor = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def fix(self) -> int:
        """Gets or sets the fix number for the current XML file."""
        try:
            dotnet_result = self._dotnet_instance.Fix
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @fix.setter
    def fix(self, value: int):
        """Gets or sets the fix number for the current XML file."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Fix = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def build(self) -> int:
        """Gets or sets the build number for the current XML file."""
        try:
            dotnet_result = self._dotnet_instance.Build
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @build.setter
    def build(self, value: int):
        """Gets or sets the build number for the current XML file."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Build = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def to_string(self) -> str:
        """Converts the value of the current niveristand.XMLVersionInfo object to a string.

        Returns:
            str: A string representing the niveristand.XMLVersionInfo object in the following format: Major.Minor.Fix.Build.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToString(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @overload
    def equals(self, obj: Any) -> bool:
        """Determines whether the current niveristand.XMLVersionInfo is equal to the specified obj.

        Args:
            obj: The object to compare with the current niveristand.XMLVersionInfo.

        Returns:
            bool: true if the specified obj is equal to the current instance of niveristand.XMLVersionInfo. Otherwise, false.
        """

    @overload
    def equals(self, other: XMLVersionInfo) -> bool:
        """Determines whether the current niveristand.XMLVersionInfo is equal to the specified niveristand.XMLVersionInfo.

        Args:
            other: The niveristand.XMLVersionInfo to compare to the current niveristand.XMLVersionInfo.

        Returns:
            bool: true if the specified niveristand.XMLVersionInfo is equal to the current instance of niveristand.XMLVersionInfo. Otherwise, false.
        """

    def equals(self, *args):
        """Determines whether the current niveristand.XMLVersionInfo is equal to the specified obj."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Gets a hashcode of the current niveristand.XMLVersionInfo object.

        Returns:
            int: A hashcode for the current niveristand.XMLVersionInfo.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def clone(self) -> Any:
        """Creates a new niveristand.XMLVersionInfo object with the same major, minor, fix, and build numbers as the current niveristand.XMLVersionInfo object.

        Returns:
            Any: A new niveristand.XMLVersionInfo object with the same major, minor, fix, and build numbers as the current niveristand.XMLVersionInfo object.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.Clone(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @overload
    def compare_to(self, other: Any) -> int:
        """Compares the current niveristand.XMLVersionInfo to another object and returns a value indicating whether the current niveristand.XMLVersionInfo is older, newer, or equal to the object.

        Args:
            other: The object to compare to niveristand.XMLVersionInfo. Must be an niveristand.XMLVersionInfo object.

        Returns:
            int: If the current niveristand.XMLVersionInfo is older than other, returns -1. If the two are equal, returns 0. If the current instance is newer than other or other is null, returns 1.
        """

    @overload
    def compare_to(self, other: XMLVersionInfo) -> int:
        """Compares the current niveristand.XMLVersionInfo to another niveristand.XMLVersionInfo and returns a value indicating whether the current niveristand.XMLVersionInfo is older, newer, or equal to other.

        Args:
            other: The niveristand.XMLVersionInfo to compare to the current niveristand.XMLVersionInfo.

        Returns:
            int: If the current niveristand.XMLVersionInfo is older than other, returns -1. If the two are equal, returns 0. If the current instance is newer than other or other is null, returns 1.
        """

    def compare_to(self, *args):
        """Compares the current niveristand.XMLVersionInfo to another object and returns a value indicating whether the current niveristand.XMLVersionInfo is older, newer, or equal to the object."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.CompareTo(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def __eq__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance == other._dotnet_instance
        return NotImplemented

    def __ne__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance != other._dotnet_instance
        return NotImplemented

    def __lt__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance < other._dotnet_instance
        return NotImplemented

    def __gt__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance > other._dotnet_instance
        return NotImplemented

    def __le__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance <= other._dotnet_instance
        return NotImplemented

    def __ge__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance >= other._dotnet_instance
        return NotImplemented


@_register_dotnet_type(NationalInstruments.VeriStand.DataArray)
class DataArray(_DotNetBase):
    """Represents NI VeriStand channel and parameter data as an array of scalar, vector or matrix values."""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.DataArray class."""

    @overload
    def __init__(self, other: DataArray):
        """Initializes a new instance of niveristand.DataArray by copying an existing instance.

        Args:
            other: The instance of niveristand.DataArray to copy.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def value(self) -> Sequence[float]:
        """An array that contains the values stored in niveristand.DataArray. If niveristand.DataArray represents a scalar value, will contain a single element set to the scalar value. If niveristand.DataArray represents vector values, niveristand.DataArray.value represents a one-dimensional array of vector values. If niveristand.DataArray represents matrix values, niveristand.DataArray.value represents a one-dimensional array that stores the matrix values in column-major order."""
        try:
            dotnet_result = self._dotnet_instance.Value
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @value.setter
    def value(self, value: Sequence[float]):
        """An array that contains the values stored in niveristand.DataArray. If niveristand.DataArray represents a scalar value, will contain a single element set to the scalar value. If niveristand.DataArray represents vector values, niveristand.DataArray.value represents a one-dimensional array of vector values. If niveristand.DataArray represents matrix values, niveristand.DataArray.value represents a one-dimensional array that stores the matrix values in column-major order."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Value = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def dim(self) -> Sequence[int]:
        """An array that stores the dimensions of the niveristand.DataArray. If niveristand.DataArray.dim is null, Value[0] represents a scalar value."""
        try:
            dotnet_result = self._dotnet_instance.Dim
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @dim.setter
    def dim(self, value: Sequence[int]):
        """An array that stores the dimensions of the niveristand.DataArray. If niveristand.DataArray.dim is null, Value[0] represents a scalar value."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Dim = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @overload
    def equals(self, other: DataArray) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.DataArray.

        Args:
            other: The niveristand.DataArray object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance niveristand.DataArray. Otherwise, false.
        """

    @overload
    def equals(self, obj: Any) -> bool:
        """Determines whether the specified obj is equal to the current instance of niveristand.DataArray.

        Args:
            obj: The object to compare with the current niveristand.DataArray object. Must be a niveristand.DataArray object.

        Returns:
            bool: true if the specified obj is equal to the current instance niveristand.DataArray. Otherwise, false.
        """

    def equals(self, *args):
        """Determines whether the specified other object is equal to the current instance of niveristand.DataArray."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Gets a hashcode for the current niveristand.DataArray object. The hash code this method returns is suitable for use in hashing algorithms and data structures like a hash table.

        Returns:
            int: A hashcode for the current niveristand.DataArray.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def __eq__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance == other._dotnet_instance
        return NotImplemented

    def __ne__(self, other):
        if isinstance(other, _DotNetBase):
            return self._dotnet_instance != other._dotnet_instance
        return NotImplemented

    def is_scalar(self) -> bool:
        """Determines if the data in the niveristand.DataArray is scalar.

        Returns:
            bool: true if the current niveristand.DataArray is scalar. Otherwise, false.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.IsScalar(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_double(self) -> float:
        """If the niveristand.DataArray is scalar, returns the value of the niveristand.DataArray instance as a double-precision floating-point number. If the data is not scalar, throws an exception.

        Returns:
            float: The value of this instance as a double-precision floating-point number.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToDouble(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def from_double(self, val: float):
        """Sets the stored value of niveristand.DataArray to the specified double-precision floating point number. Overwrites any data in the niveristand.DataArray.

        Args:
            val: The value with which to initialize a new instance of niveristand.DataArray.
        """
        unwrapped = _unwrap(None, val)
        try:
            dotnet_result = self._dotnet_instance.FromDouble(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def is_matrix(self) -> bool:
        """Determines if the data in the niveristand.DataArray is a matrix. Requires that the dimensions are defined, but returns true if the niveristand.DataArray contains a valid matrix or vector.

        Returns:
            bool: true if the current niveristand.DataArray can be interpreted as a non-scalar matrix. Otherwise, false.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.IsMatrix(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_matrix(self) -> Sequence[Sequence[float]]:
        """If the niveristand.DataArray is non-scalar, returns the value of the niveristand.DataArray instance as a 2D array in row-major format.

        Returns:
            Sequence[Sequence[float]]: The value of this instance as a 2D array.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToMatrix(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def from_matrix(self, mtx: Sequence[Sequence[float]]):
        """Sets the stored value of niveristand.DataArray to a matrix of the specified dimensions and values.

        Args:
            mtx: The 2D array that defines the dimensions and values of the matrix.
        """
        unwrapped = _unwrap({None: ((), (('__array2d__', 'System.Double'),))}, mtx)
        try:
            dotnet_result = self._dotnet_instance.FromMatrix(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def is_vector(self) -> bool:
        """Determines if the data in the niveristand.DataArray is a non-scalar vector in form of 1xN. (niveristand.DataArray.dim must be defined)

        Returns:
            bool: true if the current niveristand.DataArray is a vector. Otherwise, false.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.IsVector(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_vector(self) -> Sequence[float]:
        """If the niveristand.DataArray is a vector, returns the value of the niveristand.DataArray instance as an array.

        Returns:
            Sequence[float]: The value niveristand.DataArray as an array.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToVector(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def from_vector(self, vec: Sequence[float]):
        """Sets the value of niveristand.DataArray to the specified one-dimensional vector.

        Args:
            vec: The array of values with which to initialize niveristand.DataArray.
        """
        unwrapped = _unwrap(None, vec)
        try:
            dotnet_result = self._dotnet_instance.FromVector(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.VeriStandException)
class VeriStandException(Exception):
    """Represents the errors, warnings, or messages that occur when NI VeriStand encounters an error."""

    def __str__(self) -> str:
        return str(self._dotnet_instance.Message)

    @overload
    def __init__(self, code: int):
        """Initializes a new instance of the niveristand.VeriStandException class with the specified integral error code.

        Args:
            code: The integral error code that caused the exception to be thrown.
        """

    @overload
    def __init__(self, code: ErrorCode):
        """Initializes a new instance of the niveristand.VeriStandException class with the specified niveristand.ErrorCode.

        Args:
            code: The niveristand.ErrorCode that caused the exception to be thrown.
        """

    @overload
    def __init__(self, code: int, message: str):
        """Initializes a new instance of the niveristand.VeriStandException class with the specified integral error code and error message.

        Args:
            code: The integral error code that caused the exception to be thrown.
            message: The error message associated with the exception.
        """

    @overload
    def __init__(self, code: ErrorCode, message: str):
        """Initializes a new instance of the niveristand.VeriStandException class with the specified niveristand.ErrorCode and error message.

        Args:
            code: niveristand.ErrorCode that caused the exception to be thrown.
            message: The error message associated with the exception.
        """

    @overload
    def __init__(self, code: int, message: str, inner_exception: System.Exception):
        """Initializes a new instance of the niveristand.VeriStandException class with the specified integral error code, error message, and inner exception.

        Args:
            code: The integral error code that caused the exception to be thrown.
            message: The error message associated with the exception.
            inner_exception: The inner exception that caused this exception to be thrown.
        """

    @overload
    def __init__(self, code: ErrorCode, message: str, inner_exception: System.Exception):
        """Initializes a new instance of the niveristand.VeriStandException class with the specified niveristand.ErrorCode, error message, and inner exception.

        Args:
            code: The niveristand.ErrorCode that caused the exception to be thrown.
            message: The error message associated with the exception.
            inner_exception: The inner exception that caused this exception to be thrown.
        """

    @overload
    def __init__(self, error: VeriStandError):
        """Initializes a new instance of the niveristand.VeriStandException class with the specified niveristand.Error.

        Args:
            error: The niveristand.Error that caused the exception to be thrown.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def code(self) -> int:
        """Gets or sets the error code of the current niveristand.VeriStandException."""
        try:
            dotnet_result = self._dotnet_instance.Code
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @code.setter
    def code(self, value: int):
        """Gets or sets the error code of the current niveristand.VeriStandException."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Code = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def resolved_error_message(self) -> str:
        """Gets or sets a resolved error message for the current instance of niveristand.VeriStandException."""
        try:
            dotnet_result = self._dotnet_instance.ResolvedErrorMessage
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.ChannelGroupMissingFromLogFileException, error_code="ChannelGroupNotFoundInLogFile")
class ChannelGroupMissingFromLogFileException(VeriStandException):
    """Represents errors, warnings, or messages that occur when a channel group is not found in a file."""

    @overload
    def __init__(self, file_name: str, channel_group: str):
        """Initializes a new instance of the niveristand.ChannelGroupMissingFromLogFileException class.

        Args:
            file_name: The name of the log file.
            channel_group: The name of the channel group.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.ChannelMissingFromLogFileException, error_code="ChannelNotFoundInLogFile")
class ChannelMissingFromLogFileException(VeriStandException):
    """Represents errors, warnings, or messages that occur when a channel is not found in a channel group."""

    @overload
    def __init__(self, file_name: str, channel_group: str, channel: str):
        """Initializes a new instance of the niveristand.ChannelMissingFromLogFileException class.

        Args:
            file_name: The name of the log file.
            channel_group: The name of the channel group.
            channel: The name of the channel.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.ChannelNotFoundException, error_code="NotAChannel")
class ChannelNotFoundException(VeriStandException):
    """Used for not found channels."""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.ChannelNotFoundException class."""

    @overload
    def __init__(self, channel_name: str):
        """Initializes a new instance of the niveristand.ChannelNotFoundException class.

        Args:
            channel_name: name of not found channel
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.DependenciesCycleException, error_code="DependenciesCycle")
class DependenciesCycleException(VeriStandException):
    """Represents errors, warnings, or messages that occur when an operation can't be performed because some input parameter is bad."""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.DependenciesCycleException class."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.GatewayNotOnLocalhostException, error_code="GatewayNotOnLocalhost")
class GatewayNotOnLocalhostException(VeriStandException):
    """Represents errors, warnings, or messages that occur when a certain feature needs the getaway to be running on the localhost and the gateway runs on a different machine."""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.GatewayNotOnLocalhostException class."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.ParameterFileParseException, error_code="ModelParameterFileParseError")
class ParameterFileParseException(VeriStandException):
    """Represents errors, warnings, or messages that occur when the model parameter parser encounters an invalid or incorrectly formatted file."""

    @overload
    def __init__(self, message: str):
        """Initializes a new instance of the niveristand.ParameterFileParseException class with the specified error message.

        Args:
            message: The error message associated with this exception.
        """

    @overload
    def __init__(self, message: str, inner_exception: System.Exception):
        """Initializes a new instance of the niveristand.ParameterFileParseException class with the specified error message and inner exception.

        Args:
            message: The error message associated with this exception.
            inner_exception: The inner exception that caused this exception to be thrown.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.STIFileException, error_code="STIFileError")
class STIFileException(VeriStandException):
    """Exception used by STI conversions."""

    @overload
    def __init__(self, error_message: str):
        """Initializes a new instance of the niveristand.STIFileException class.

        Args:
            error_message: contained error message
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.SequenceFileParseException, error_code="InvalidFile")
class SequenceFileParseException(VeriStandException):
    """Represents errors, warnings, or messages that occur when NI VeriStand fails to parse a real-time sequence."""

    @overload
    def __init__(self, message: str):
        """Initializes a new instance of the niveristand.SequenceFileParseException class with the specified error message.

        Args:
            message: The error message associated with this exception.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.SequenceNotFoundException, error_code="SequenceNotFoundInSession")
class SequenceNotFoundException(VeriStandException):
    """Represents errors, warnings, or messages that occur when a real-time sequence is not found in a stimulus profile session."""

    @overload
    def __init__(self, sequence_name: str):
        """Initializes a new instance of the niveristand.SequenceNotFoundException class with the specified real-time sequence.

        Args:
            sequence_name: The name of the real-time sequence.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.StimulusProfileSessionNotDeployedException, error_code="SessionNotDeployed")
class StimulusProfileSessionNotDeployedException(VeriStandException):
    """Represents errors, warnings, or messages that occur when a stimulus profile session is not deployed."""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.StimulusProfileSessionNotDeployedException class."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionNotDeployedException, error_code="NotDeployed")
class SystemDefinitionNotDeployedException(VeriStandException):
    """Represents errors, warnings, or messages that occur when a system definition is not deployed."""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.SystemDefinitionNotDeployedException class."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.UnexpectedErrorException, error_code="UnexpectedError")
class UnexpectedErrorException(VeriStandException):
    """Represents an unexpected error situation"""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.UnexpectedErrorException class."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)
