"""Module for NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport."""

from __future__ import annotations

from typing import Any, Dict, Iterable, overload, Sequence, Tuple

import clr

clr.AddReference("NationalInstruments.VeriStand.SystemDefinitionAPI")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport  # type: ignore
import System  # type: ignore

from ..._autogenerated_utils import *
from ... import *


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.IModelDescriptor, False)
class IModelDescriptor(_DotNetBase):
    """Holds information from the model descriptor"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def model_name(self) -> str:
        """Name of the model"""
        try:
            dotnet_result = self._dotnet_instance.ModelName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def model_generation_toolchain_version(self) -> Tuple[int, int, int, int]:
        """Version of the tool that was used to generate the model"""
        try:
            dotnet_result = self._dotnet_instance.ModelGenerationToolchainVersion
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def model_version(self) -> Tuple[int, int, int, int]:
        """Version of the model"""
        try:
            dotnet_result = self._dotnet_instance.ModelVersion
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def author(self) -> str:
        """Model author"""
        try:
            dotnet_result = self._dotnet_instance.Author
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def model_description(self) -> str:
        """Description of the model"""
        try:
            dotnet_result = self._dotnet_instance.ModelDescription
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def target_platforms(self) -> Iterable[str]:
        """Target platforms supported by the model"""
        try:
            dotnet_result = self._dotnet_instance.TargetPlatforms
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.ModelParamType)
class ModelParamType(_DotNetBase):
    """RESERVED FOR INTERNAL USE. Wraps model parameter information."""

    @overload
    def __init__(self, idx: int, id: str, name: str, type: int, dims: Sequence[int], value: Sequence[float]):
        """RESERVED FOR INTERNAL USE."""

    @overload
    def __init__(self, idx: int, id: str, name: str, type: int, dims: Sequence[int], value: Sequence[float], enum_value_table: Sequence[Tuple[str,int]], enum_class_name: str):
        """Overload Constructor to set EnumValueTable for parameters"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args, unwrap_spec={(int, str, str, int, Sequence[int], Sequence[float]): ((), ()), (int, str, str, int, Sequence[int], Sequence[float], Sequence[Tuple[str,int]], str): ((), (None, None, None, None, None, None, ('System.Collections.Generic.IList`1', ('System.Tuple`2', 'System.String', 'System.Int32')), None))})

    @property
    def idx(self) -> int:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Idx
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def id(self) -> str:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.ID
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def name(self) -> str:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Name
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def data_type(self) -> int:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.DataType
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def enum_class_name(self) -> str:
        """EnumClassName for parameters"""
        try:
            dotnet_result = self._dotnet_instance.EnumClassName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def dims(self) -> Sequence[int]:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Dims
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def value(self) -> Sequence[float]:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Value
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def enum_value_table(self) -> Sequence[Tuple[str,int]]:
        """EnumValueTable for parameters"""
        try:
            dotnet_result = self._dotnet_instance.EnumValueTable
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_value_table.setter
    def enum_value_table(self, value: Sequence[Tuple[str,int]]):
        """EnumValueTable for parameters"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', ('System.Tuple`2', 'System.String', 'System.Int32')),))}, value)
        try:
            self._dotnet_instance.EnumValueTable = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def _custom_repr(self) -> str:
        return f"(name={self.name})"


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.ModelPortType)
class ModelPortType(_DotNetBase):
    """RESERVED FOR INTERNAL USE. Wraps model port information."""

    @overload
    def __init__(self, name: str, index: int, task_id: int, is_input: bool, dims: Sequence[int]):
        """RESERVED FOR INTERNAL USE."""

    @overload
    def __init__(self, name: str, index: int, task_id: int, is_input: bool, dims: Sequence[int], enum_value_table: Sequence[Tuple[str,int]], enum_class_name: str):
        """Overload Constructor to set EnumValueTable for inports and outports"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args, unwrap_spec={(str, int, int, bool, Sequence[int]): ((), ()), (str, int, int, bool, Sequence[int], Sequence[Tuple[str,int]], str): ((), (None, None, None, None, None, ('System.Collections.Generic.IList`1', ('System.Tuple`2', 'System.String', 'System.Int32')), None))})

    @property
    def name(self) -> str:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Name
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def index(self) -> int:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Index
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def task_id(self) -> int:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.TaskID
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def is_input(self) -> bool:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.IsInput
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def enum_class_name(self) -> str:
        """EnumClassName for inports and outports"""
        try:
            dotnet_result = self._dotnet_instance.EnumClassName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def dims(self) -> Sequence[int]:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Dims
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def enum_value_table(self) -> Sequence[Tuple[str,int]]:
        """EnumValueTable for inports and outports"""
        try:
            dotnet_result = self._dotnet_instance.EnumValueTable
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_value_table.setter
    def enum_value_table(self, value: Sequence[Tuple[str,int]]):
        """EnumValueTable for inports and outports"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', ('System.Tuple`2', 'System.String', 'System.Int32')),))}, value)
        try:
            self._dotnet_instance.EnumValueTable = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def _custom_repr(self) -> str:
        return f"(name={self.name})"


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.ModelSignalType)
class ModelSignalType(_DotNetBase):
    """RESERVED FOR INTERNAL USE. Wraps signal info from a model."""

    @overload
    def __init__(self, idx: int, id: str, name: str, block_name: str, port_number: int, datatype: int, dims: Sequence[int]):
        """RESERVED FOR INTERNAL USE."""

    @overload
    def __init__(self, idx: int, id: str, name: str, block_name: str, port_number: int, datatype: int, dims: Sequence[int], enum_value_table: Sequence[Tuple[str,int]], enum_class_name: str):
        """Overload Constructor to set EnumValueTable for signals"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args, unwrap_spec={(int, str, str, str, int, int, Sequence[int]): ((), ()), (int, str, str, str, int, int, Sequence[int], Sequence[Tuple[str,int]], str): ((), (None, None, None, None, None, None, None, ('System.Collections.Generic.IList`1', ('System.Tuple`2', 'System.String', 'System.Int32')), None))})

    @property
    def idx(self) -> int:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Idx
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def id(self) -> str:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.ID
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def name(self) -> str:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Name
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def block_name(self) -> str:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.BlockName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def data_type(self) -> int:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.DataType
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def port_number(self) -> int:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.PortNumber
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def enum_class_name(self) -> str:
        """EnumClassName for signals"""
        try:
            dotnet_result = self._dotnet_instance.EnumClassName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def dims(self) -> Sequence[int]:
        """RESERVED FOR INTERNAL USE."""
        try:
            dotnet_result = self._dotnet_instance.Dims
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def enum_value_table(self) -> Sequence[Tuple[str,int]]:
        """EnumValueTable for signals"""
        try:
            dotnet_result = self._dotnet_instance.EnumValueTable
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_value_table.setter
    def enum_value_table(self, value: Sequence[Tuple[str,int]]):
        """EnumValueTable for signals"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', ('System.Tuple`2', 'System.String', 'System.Int32')),))}, value)
        try:
            self._dotnet_instance.EnumValueTable = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def _custom_repr(self) -> str:
        return f"(name={self.name})"


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelEnumTypeDefinitionItems)
class VsModelEnumTypeDefinitionItems(_DotNetBase):
    """VsModelEnumTypeDefinitionItems type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def enum_values(self) -> Sequence[int]:
        """Enum Values for the enum"""
        try:
            dotnet_result = self._dotnet_instance.EnumValues
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_values.setter
    def enum_values(self, value: Sequence[int]):
        """Enum Values for the enum"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', 'System.Int32'),))}, value)
        try:
            self._dotnet_instance.EnumValues = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def enum_names(self) -> Sequence[str]:
        """Enum name for the enum"""
        try:
            dotnet_result = self._dotnet_instance.EnumNames
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_names.setter
    def enum_names(self, value: Sequence[str]):
        """Enum name for the enum"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', 'System.String'),))}, value)
        try:
            self._dotnet_instance.EnumNames = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelFeatureSet)
class VsModelFeatureSet(_DotNetBase):
    """Provides information about supported features of a specific version of .vsmodel"""

    @overload
    def __init__(self, vsmodel_version: str):
        """Parameterized constructor

        Args:
            vsmodel_version: model descriptor version as string
        """

    @overload
    def __init__(self, vsmodel_version: Tuple[int, int, int, int]):
        """Parameterized constructor

        Args:
            vsmodel_version: model descriptor version
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args, unwrap_spec={(str,): ((), ()), (Tuple[int, int, int, int],): ((), ('System.Version',))})

    @_staticproperty
    def first_released_vs_model_addon_version_string() -> str:
        """The first released VsModel addon version as string"""
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelFeatureSet.FirstReleasedVsModelAddonVersionString
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @_staticproperty
    def highest_supported_vs_model_addon_version_string() -> str:
        """Highest supported VsModel addon version as string"""
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelFeatureSet.HighestSupportedVsModelAddonVersionString
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def supports_non_virtual_bus(self) -> bool:
        """Indicates whether the vsmodel has support for non virtual buses"""
        try:
            dotnet_result = self._dotnet_instance.SupportsNonVirtualBus
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def generated_using_latest_addon_version(self) -> bool:
        """Indicates whether the vsmodel was built with the latest VsModel addon"""
        try:
            dotnet_result = self._dotnet_instance.GeneratedUsingLatestAddonVersion
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def supports_signals(self) -> bool:
        """Indicates whether the vsmodel has support for signals"""
        try:
            dotnet_result = self._dotnet_instance.SupportsSignals
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelItemBaseType)
class VsModelItemBaseType(_DotNetBase):
    """Class containing information about a model item type. The item can be input, output or parameter"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def name(self) -> str:
        """Name of the element"""
        try:
            dotnet_result = self._dotnet_instance.Name
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @name.setter
    def name(self, value: str):
        """Name of the element"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Name = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def data_type(self) -> str:
        """Model item data type"""
        try:
            dotnet_result = self._dotnet_instance.DataType
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @data_type.setter
    def data_type(self, value: str):
        """Model item data type"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.DataType = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def c_api_type(self) -> str:
        """Type used by Simulink in the generated C code"""
        try:
            dotnet_result = self._dotnet_instance.CApiType
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @c_api_type.setter
    def c_api_type(self, value: str):
        """Type used by Simulink in the generated C code"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.CApiType = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def dimensions(self) -> Any:
        """Model item dimensions"""
        try:
            dotnet_result = self._dotnet_instance.Dimensions
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @dimensions.setter
    def dimensions(self, value: Any):
        """Model item dimensions"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Dimensions = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def elements(self) -> Sequence[VsModelElement]:
        """Model item elements - has content when the item is Bus"""
        try:
            dotnet_result = self._dotnet_instance.Elements
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @elements.setter
    def elements(self, value: Sequence[VsModelElement]):
        """Model item elements - has content when the item is Bus"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Elements = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def enum_class_name(self) -> str:
        """Model item EnumClassName"""
        try:
            dotnet_result = self._dotnet_instance.EnumClassName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_class_name.setter
    def enum_class_name(self, value: str):
        """Model item EnumClassName"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.EnumClassName = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def is_valid(self) -> bool:
        """Verifies if the input/output/parameter is valid based on VeriStand's current support

        Returns:
            bool: True if all conditions are met, false otherwise
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.IsValid(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def is_supported_fixed_point_type(self) -> bool:
        """Verifies if the input/output/parameter is a supported fixed point type. For now all fixed point types for which the corresponding C api type is a base type are supported.

        Returns:
            bool: True if it is a supported fixed point type, false otherwise.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.IsSupportedFixedPointType(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def _custom_repr(self) -> str:
        return f"(name={self.name})"


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelItemType)
class VsModelItemType(VsModelItemBaseType):
    """Model item type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def unit(self) -> str:
        """Model item unit"""
        try:
            dotnet_result = self._dotnet_instance.Unit
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @unit.setter
    def unit(self, value: str):
        """Model item unit"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Unit = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelJsonFileDescriptor)
class VsModelJsonFileDescriptor(_DotNetBase):
    """Class containing information for deserializing the VsModel descriptor JSON file"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def version(self) -> str:
        """Model version"""
        try:
            dotnet_result = self._dotnet_instance.Version
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @version.setter
    def version(self, value: str):
        """Model version"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Version = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def model_name(self) -> str:
        """Model name"""
        try:
            dotnet_result = self._dotnet_instance.ModelName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @model_name.setter
    def model_name(self, value: str):
        """Model name"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.ModelName = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def metadata(self) -> VsModelMetadata:
        """Model metadata"""
        try:
            dotnet_result = self._dotnet_instance.Metadata
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @metadata.setter
    def metadata(self, value: VsModelMetadata):
        """Model metadata"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Metadata = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def inports(self) -> Sequence[VsModelInport]:
        """Inport list"""
        try:
            dotnet_result = self._dotnet_instance.Inports
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @inports.setter
    def inports(self, value: Sequence[VsModelInport]):
        """Inport list"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.List`1', 'NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelInport'),))}, value)
        try:
            self._dotnet_instance.Inports = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def outports(self) -> Sequence[VsModelOutport]:
        """Outport list"""
        try:
            dotnet_result = self._dotnet_instance.Outports
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @outports.setter
    def outports(self, value: Sequence[VsModelOutport]):
        """Outport list"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.List`1', 'NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelOutport'),))}, value)
        try:
            self._dotnet_instance.Outports = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def parameters(self) -> Sequence[VsModelParameter]:
        """Parameter list"""
        try:
            dotnet_result = self._dotnet_instance.Parameters
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @parameters.setter
    def parameters(self, value: Sequence[VsModelParameter]):
        """Parameter list"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.List`1', 'NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelParameter'),))}, value)
        try:
            self._dotnet_instance.Parameters = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def signals(self) -> Sequence[VsModelSignal]:
        """Signals list"""
        try:
            dotnet_result = self._dotnet_instance.Signals
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @signals.setter
    def signals(self, value: Sequence[VsModelSignal]):
        """Signals list"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IList`1', 'NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelSignal'),))}, value)
        try:
            self._dotnet_instance.Signals = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def enum_type_definitions(self) -> Dict[str,VsModelEnumTypeDefinitionItems]:
        """EnumTypeDefinitions dictionary"""
        try:
            dotnet_result = self._dotnet_instance.EnumTypeDefinitions
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_type_definitions.setter
    def enum_type_definitions(self, value: Dict[str,VsModelEnumTypeDefinitionItems]):
        """EnumTypeDefinitions dictionary"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IReadOnlyDictionary`2', 'System.String', 'NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelEnumTypeDefinitionItems'),))}, value)
        try:
            self._dotnet_instance.EnumTypeDefinitions = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelJsonFileDescriptorUtilities, False)
class VsModelJsonFileDescriptorUtilities(_DotNetBase):
    """Utility methods for VsModelJsonFileDescriptor"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    def get_dimensions(dimensions: Any) -> Sequence[int]:
        """Returns int dimensions for the current item. Scalar and multidimensional array have dimensions contained into an array, but the unidimensional array only has a scalar value (length of the array). We consider unidimensional array to have dimensions: [N, 1].

        Args:
            dimensions: dimensions data read from JSON

        Returns:
            Sequence[int]: array of dimensions
        """
        unwrapped = _unwrap(None, dimensions)
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelJsonFileDescriptorUtilities.GetDimensions(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def is_scalar(dimensions: Any) -> bool:
        """Returns whether the specified dimensions belong to a scalar element

        Args:
            dimensions: dimensions object

        Returns:
            bool: True, if dimensions match a scalar element, false otherwise
        """
        unwrapped = _unwrap(None, dimensions)
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelJsonFileDescriptorUtilities.IsScalar(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelMetadata)
class VsModelMetadata(_DotNetBase):
    """VsModel metadata"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def slx_file_path(self) -> str:
        """.slx file path"""
        try:
            dotnet_result = self._dotnet_instance.SLXFilePath
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @slx_file_path.setter
    def slx_file_path(self, value: str):
        """.slx file path"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.SLXFilePath = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def simulink_release(self) -> str:
        """Simulink release"""
        try:
            dotnet_result = self._dotnet_instance.SimulinkRelease
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @simulink_release.setter
    def simulink_release(self, value: str):
        """Simulink release"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.SimulinkRelease = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def simulink_version(self) -> str:
        """Simulink version"""
        try:
            dotnet_result = self._dotnet_instance.SimulinkVersion
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @simulink_version.setter
    def simulink_version(self, value: str):
        """Simulink version"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.SimulinkVersion = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def release_description(self) -> str:
        """Simulink release description"""
        try:
            dotnet_result = self._dotnet_instance.ReleaseDescription
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @release_description.setter
    def release_description(self, value: str):
        """Simulink release description"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.ReleaseDescription = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def author(self) -> str:
        """Model file author"""
        try:
            dotnet_result = self._dotnet_instance.Author
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @author.setter
    def author(self, value: str):
        """Model file author"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Author = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def description(self) -> str:
        """Model description"""
        try:
            dotnet_result = self._dotnet_instance.Description
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @description.setter
    def description(self, value: str):
        """Model description"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Description = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def model_version(self) -> str:
        """Model version"""
        try:
            dotnet_result = self._dotnet_instance.ModelVersion
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @model_version.setter
    def model_version(self, value: str):
        """Model version"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.ModelVersion = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def time_step(self) -> str:
        """Model time step"""
        try:
            dotnet_result = self._dotnet_instance.TimeStep
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @time_step.setter
    def time_step(self, value: str):
        """Model time step"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.TimeStep = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def target_platforms(self) -> Sequence[str]:
        """Target platform the model was compiled for"""
        try:
            dotnet_result = self._dotnet_instance.TargetPlatforms
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @target_platforms.setter
    def target_platforms(self, value: Sequence[str]):
        """Target platform the model was compiled for"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.List`1', 'System.String'),))}, value)
        try:
            self._dotnet_instance.TargetPlatforms = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def bitness(self) -> int:
        """Model bitness"""
        try:
            dotnet_result = self._dotnet_instance.Bitness
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @bitness.setter
    def bitness(self, value: int):
        """Model bitness"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Bitness = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def number_of_sample_times(self) -> int:
        """Number of sample times"""
        try:
            dotnet_result = self._dotnet_instance.NumberOfSampleTimes
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @number_of_sample_times.setter
    def number_of_sample_times(self, value: int):
        """Number of sample times"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.NumberOfSampleTimes = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def external_mode(self) -> str:
        """External mode setting: on or off"""
        try:
            dotnet_result = self._dotnet_instance.ExternalMode
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @external_mode.setter
    def external_mode(self, value: str):
        """External mode setting: on or off"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.ExternalMode = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelParameter)
class VsModelParameter(VsModelItemType):
    """Parameter type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def default_value(self) -> Any:
        """Default value"""
        try:
            dotnet_result = self._dotnet_instance.DefaultValue
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @default_value.setter
    def default_value(self, value: Any):
        """Default value"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.DefaultValue = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelSignal)
class VsModelSignal(VsModelItemType):
    """Signal type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def block_path(self) -> str:
        """Name of the source block for the signal."""
        try:
            dotnet_result = self._dotnet_instance.BlockPath
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @block_path.setter
    def block_path(self, value: str):
        """Name of the source block for the signal."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.BlockPath = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def port_number(self) -> int:
        """Port number of the block that is the source of the signal."""
        try:
            dotnet_result = self._dotnet_instance.PortNumber
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @port_number.setter
    def port_number(self, value: int):
        """Port number of the block that is the source of the signal."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.PortNumber = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def signal_label(self) -> str:
        """Name of the signal"""
        try:
            dotnet_result = self._dotnet_instance.SignalLabel
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @signal_label.setter
    def signal_label(self, value: str):
        """Name of the signal"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.SignalLabel = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def is_connected_to_virtual_bus(self) -> bool:
        """Whether the signal is connected to a virtual bus."""
        try:
            dotnet_result = self._dotnet_instance.IsConnectedToVirtualBus
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @is_connected_to_virtual_bus.setter
    def is_connected_to_virtual_bus(self, value: bool):
        """Whether the signal is connected to a virtual bus."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.IsConnectedToVirtualBus = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.FmuModelDescriptor)
class FmuModelDescriptor(IModelDescriptor):
    """Holds information from the model descriptor"""

    @overload
    def __init__(self, model_path: str):
        """Initializes a new instance of the niveristand.systemdefinitionapi.modelsupport.FmuModelDescriptor class.

        Args:
            model_path: Model File Path
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def target_platforms(self) -> Iterable[str]:
        """Target platforms supported by the model"""
        try:
            dotnet_result = self._dotnet_instance.TargetPlatforms
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @target_platforms.setter
    def target_platforms(self, value: Iterable[str]):
        """Target platforms supported by the model"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IEnumerable`1', 'System.String'),))}, value)
        try:
            self._dotnet_instance.TargetPlatforms = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def fmi_version(self) -> str:
        """FMI version"""
        try:
            dotnet_result = self._dotnet_instance.FmiVersion
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @fmi_version.setter
    def fmi_version(self, value: str):
        """FMI version"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.FmiVersion = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def generation_tool(self) -> str:
        """Model generation tool"""
        try:
            dotnet_result = self._dotnet_instance.GenerationTool
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @generation_tool.setter
    def generation_tool(self, value: str):
        """Model generation tool"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.GenerationTool = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def fmu_file_size(self) -> int:
        """Model file size"""
        try:
            dotnet_result = self._dotnet_instance.FmuFileSize
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelDescriptorExtended)
class VsModelDescriptorExtended(VsModelJsonFileDescriptor, IModelDescriptor):
    """VsModel descriptor containing both information needed for deserialization and other vsmodel properties"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def enum_value_table_by_enum_class_name(self) -> dict[str, Sequence[Tuple[str, int]]]:
        """EnumValueTable by enum class name of the model"""
        try:
            dotnet_result = self._dotnet_instance.EnumValueTableByEnumClassName
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @enum_value_table_by_enum_class_name.setter
    def enum_value_table_by_enum_class_name(self, value: dict[str, Sequence[Tuple[str, int]]]):
        """EnumValueTable by enum class name of the model"""
        unwrapped = _unwrap({None: ((), (('System.Collections.Generic.IReadOnlyDictionary`2', 'System.String', ('System.Collections.Generic.IList`1', ('System.Tuple`2', 'System.String', 'System.Int32'))),))}, value)
        try:
            self._dotnet_instance.EnumValueTableByEnumClassName = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def deserialize_from(stream_reader: System.IO.StreamReader) -> VsModelDescriptorExtended:
        """Creates extended vsmodel descriptor from the file stream of the json descriptor

        Args:
            stream_reader: File stream that contains the json descriptor
        """
        unwrapped = _unwrap(None, stream_reader)
        try:
            dotnet_result = NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelDescriptorExtended.DeserializeFrom(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelElement)
class VsModelElement(VsModelItemBaseType):
    """Element type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelInportOutportType)
class VsModelInportOutportType(VsModelItemType):
    """Inport and Outports type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelOutport)
class VsModelOutport(VsModelInportOutportType):
    """Outport type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def is_connected_to_virtual_bus(self) -> bool:
        """Whether the outport is connected to a virtual bus."""
        try:
            dotnet_result = self._dotnet_instance.IsConnectedToVirtualBus
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @is_connected_to_virtual_bus.setter
    def is_connected_to_virtual_bus(self, value: bool):
        """Whether the outport is connected to a virtual bus."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.IsConnectedToVirtualBus = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.ModelSupport.VsModelInport)
class VsModelInport(VsModelInportOutportType):
    """Inport type"""

    @overload
    def __init__(self):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)
