"""Module for NationalInstruments.VeriStand.SystemDefinitionAPI.FPGA_Support."""

from __future__ import annotations

from typing import overload, Sequence

import clr

clr.AddReference("NationalInstruments.VeriStand.SystemDefinitionAPI")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.SystemDefinitionAPI.FPGA_Support  # type: ignore
import System  # type: ignore

from ..._autogenerated_utils import *
from ... import *


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.FPGA_Support.FPGACategory, False)
class FPGACategory(_DotNetBase):
    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def name(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Name
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def description(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Description
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def symbol(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Symbol
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def categories(self) -> Sequence[FPGACategory]:
        try:
            dotnet_result = self._dotnet_instance.Categories
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def channels(self) -> Sequence[FPGAChannel]:
        try:
            dotnet_result = self._dotnet_instance.Channels
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_string(self) -> str:
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToString(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def _custom_repr(self) -> str:
        return f"(name={self.name})"


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.FPGA_Support.FPGAChannel, False)
class FPGAChannel(_DotNetBase):
    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def name(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Name
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def category(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Category
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def symbol(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Symbol
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def description(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Description
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def unit(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.Unit
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def initial_value(self) -> float:
        try:
            dotnet_result = self._dotnet_instance.InitialValue
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def packet_index(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.PacketIndex
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def bit_offset(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.BitOffset
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def representation(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.Representation
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def scaling(self) -> float:
        try:
            dotnet_result = self._dotnet_instance.Scaling
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def scaling_offset(self) -> float:
        try:
            dotnet_result = self._dotnet_instance.ScalingOffset
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def fxpwl(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.FXPWL
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def fxpiwl(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.FXPIWL
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def period_pwm(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.PeriodPWM
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def data_offset(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.DataOffset
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def is_write(self) -> bool:
        try:
            dotnet_result = self._dotnet_instance.IsWrite
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_string(self) -> str:
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToString(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def _custom_repr(self) -> str:
        return f"(name={self.name})"


@_register_dotnet_type(NationalInstruments.VeriStand.SystemDefinitionAPI.FPGA_Support.FPGALoader)
class FPGALoader(_DotNetBase):
    @overload
    def __init__(self, file_path: str):
        ...

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def version(self) -> float:
        try:
            dotnet_result = self._dotnet_instance.Version
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def bit_file(self) -> str:
        try:
            dotnet_result = self._dotnet_instance.BitFile
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def read_packets(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.ReadPackets
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def write_packets(self) -> int:
        try:
            dotnet_result = self._dotnet_instance.WritePackets
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def categories(self) -> Sequence[FPGACategory]:
        try:
            dotnet_result = self._dotnet_instance.Categories
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def to_string(self) -> str:
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.ToString(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)
