"""Module for NationalInstruments.VeriStand.DAQPlugin."""

from __future__ import annotations

import clr

clr.AddReference("NationalInstruments.VeriStand.XMLReader")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.DAQPlugin  # type: ignore
import System  # type: ignore

from .._autogenerated_utils import *
from .. import *


@_register_dotnet_type(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, False)
class ValueDataType(_DotNetEnum):
    def __init__(self, *args):
        args_len = len(args)
        if args_len in [1,2] and type(args[0]) == NationalInstruments.VeriStand.DAQPlugin.ValueDataType:
            self._dotnet_instance = args[0]
            self._py_field_name = args[1] if args_len == 2 else ""
        else:
            raise ValueError("No instance constructor for ValueDataType")

    @_staticproperty
    def STRING() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "String")
        return ValueDataType(dotnet_result, "STRING")

    @_staticproperty
    def ENUM() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "Enum")
        return ValueDataType(dotnet_result, "ENUM")

    @_staticproperty
    def DOUBLE() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "Double")
        return ValueDataType(dotnet_result, "DOUBLE")

    @_staticproperty
    def U64() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "U64")
        return ValueDataType(dotnet_result, "U64")

    @_staticproperty
    def U32() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "U32")
        return ValueDataType(dotnet_result, "U32")

    @_staticproperty
    def U16() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "U16")
        return ValueDataType(dotnet_result, "U16")

    @_staticproperty
    def I64() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "I64")
        return ValueDataType(dotnet_result, "I64")

    @_staticproperty
    def I32() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "I32")
        return ValueDataType(dotnet_result, "I32")

    @_staticproperty
    def I16() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "I16")
        return ValueDataType(dotnet_result, "I16")

    @_staticproperty
    def BOOLEAN() -> ValueDataType:
        dotnet_result = getattr(NationalInstruments.VeriStand.DAQPlugin.ValueDataType, "Boolean")
        return ValueDataType(dotnet_result, "BOOLEAN")
