"""Module for NationalInstruments.VeriStand.ClientAPI.WaveformStreaming."""

from __future__ import annotations

from typing import Any, Callable, overload, Sequence, Tuple

import clr

clr.AddReference("NationalInstruments.VeriStand.ClientAPI")
import NationalInstruments.VeriStand  # type: ignore
import NationalInstruments.VeriStand.ClientAPI.WaveformStreaming  # type: ignore
import System  # type: ignore

from ..._autogenerated_utils import *
from ... import *


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.IWaveformStreaming', False)
class IWaveformStreaming(_DotNetBase):
    """Specifies an interface to stream waveform data from the VeriStand gateway"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    def start_streaming_waveforms(self, waveform_stream_specifications: Sequence[WaveformStreamSpecification]):
        """Starts waveform streaming for the given waveform stream specifications.

        Args:
            waveform_stream_specifications: Specifies the settings of the waveform streams.
        """
        unwrapped = _unwrap(None, waveform_stream_specifications)
        try:
            dotnet_result = self._dotnet_instance.StartStreamingWaveforms(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def stop_streaming_waveforms(self, waveform_stream_specifications: Sequence[WaveformStreamSpecification]):
        """Stops waveform streaming for the given waveform stream specifications.

        Args:
            waveform_stream_specifications: Specifies the settings of the waveform streams.
        """
        unwrapped = _unwrap(None, waveform_stream_specifications)
        try:
            dotnet_result = self._dotnet_instance.StopStreamingWaveforms(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def register_for_dbl_waveform_data(self, waveform_stream_specifications: Sequence[WaveformStreamSpecification], event_handler: Callable[[object, WaveformDataDBLEventArgs], None]):
        """Registers a delegate to receive data defined by waveform stream specifications. Waveforms must be of double data type.

        Args:
            waveform_stream_specifications: Waveform stream specifications associated with delegate. Must specify waveforms of double data type.
            event_handler: Delegate function to be called when the event is raised.
        """
        unwrapped = _unwrap({None: ((), (None, ('System.EventHandler`1', 'NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataDBLEventArgs')))}, waveform_stream_specifications, event_handler)
        try:
            dotnet_result = self._dotnet_instance.RegisterForDBLWaveformData(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def unregister_for_dbl_waveform_data(self, waveform_stream_specifications: Sequence[WaveformStreamSpecification], event_handler: Callable[[object, WaveformDataDBLEventArgs], None]):
        """Unregisters a delegate to receive data defined by waveform stream specifications. Waveforms must be of double data type.

        Args:
            waveform_stream_specifications: Waveform stream specifications to no longer associate with delegate. Must specify waveforms of double data type.
            event_handler: Delegate function that was registered to the event.
        """
        unwrapped = _unwrap({None: ((), (None, ('System.EventHandler`1', 'NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataDBLEventArgs')))}, waveform_stream_specifications, event_handler)
        try:
            dotnet_result = self._dotnet_instance.UnregisterForDBLWaveformData(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def register_for_cdb_waveform_data(self, waveform_stream_specifications: Sequence[WaveformStreamSpecification], event_handler: Callable[[object, WaveformDataCDBEventArgs], None]):
        """Registers a delegate to receive data defined by waveform stream specifications. Waveforms must be of complex double data type.

        Args:
            waveform_stream_specifications: Waveform stream specifications associated with delegate. Must specify waveforms of double data type.
            event_handler: Delegate function to be called when the event is raised.
        """
        unwrapped = _unwrap({None: ((), (None, ('System.EventHandler`1', 'NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataCDBEventArgs')))}, waveform_stream_specifications, event_handler)
        try:
            dotnet_result = self._dotnet_instance.RegisterForCDBWaveformData(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def unregister_for_cdb_waveform_data(self, waveform_stream_specifications: Sequence[WaveformStreamSpecification], event_handler: Callable[[object, WaveformDataCDBEventArgs], None]):
        """Unregisters a delegate to receive data defined by waveform stream specifications. Waveforms must be of complex double data type.

        Args:
            waveform_stream_specifications: Waveform stream specifications to no longer associate with delegate. Must specify waveforms of double data type.
            event_handler: Delegate function that was registered to the event.
        """
        unwrapped = _unwrap({None: ((), (None, ('System.EventHandler`1', 'NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataCDBEventArgs')))}, waveform_stream_specifications, event_handler)
        try:
            dotnet_result = self._dotnet_instance.UnregisterForCDBWaveformData(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_waveform_dt_values(self, waveform_paths: Sequence[str]) -> Sequence[float]:
        """Gets the dt values for multiple waveforms from the target.

        Args:
            waveform_paths: Paths of waveforms to query the dt from

        Returns:
            Sequence[float]: Time delta between samples for each of the specified waveform paths. If the waveform has not been published in the engine, the value will be NaN.
        """
        unwrapped = _unwrap(None, waveform_paths)
        try:
            dotnet_result = self._dotnet_instance.GetWaveformDtValues(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataEventArgs', False)
class WaveformDataEventArgs(_DotNetBase):
    """Provides data for waveform stream data events."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def waveform_stream_specification(self) -> WaveformStreamSpecification:
        """Gets a value indicating the waveform stream specification that defines the waveform stream."""
        try:
            dotnet_result = self._dotnet_instance.WaveformStreamSpecification
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def seconds_since_epoch(self) -> int:
        """Gets a value indicating the number of seconds since the epoch 01/01/1904 00:00:00.00 UTC (using the Gregorian calendar and ignoring leap seconds), interpreted as a 64-bit signed twos complement integer, at waveform start of the waveform stream."""
        try:
            dotnet_result = self._dotnet_instance.SecondsSinceEpoch
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def fractions_of_a_second(self) -> int:
        """Gets a value indicating the positive fractions of a second, representing the number of 2^-64 seconds, at waveform start of the waveform stream."""
        try:
            dotnet_result = self._dotnet_instance.FractionsOfASecond
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def dt(self) -> float:
        """Gets a value indicating the time interval in seconds between data points in the waveform."""
        try:
            dotnet_result = self._dotnet_instance.Dt
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def offset_from_start_in_samples(self) -> int:
        """Gets a value indicating the number of samples by which the first sample in the current data array is offset from the first sample in the waveform."""
        try:
            dotnet_result = self._dotnet_instance.OffsetFromStartInSamples
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataWatcher', False)
class WaveformDataWatcher(_DotNetBase):
    """This class serves as a wrapper around the waveform stream data event for the purpose of allowing access to this event easier to obtain from within LabVIEW. Constructing and destructing the object registers and unregisters, respectively, from the event. The set and get properties for which waveform stream specifications to watch also update the event registration. LabVIEW users can register to the event within this class for use in the event structure in LabVIEW."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def waveform_stream_specifications(self) -> Sequence[WaveformStreamSpecification]:
        """Gets or sets the waveform stream specifications associated with this WaveformDataWatcher."""
        try:
            dotnet_result = self._dotnet_instance.WaveformStreamSpecifications
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @waveform_stream_specifications.setter
    def waveform_stream_specifications(self, value: Sequence[WaveformStreamSpecification]):
        """Gets or sets the waveform stream specifications associated with this WaveformDataWatcher."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.WaveformStreamSpecifications = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    def dispose(self):
        """Explicit disposal method"""
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.Dispose(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        try:
            self._dotnet_instance.Dispose()
        except System.Exception as e:
            _wrap_exception(e)
        return False


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataWatcherCDB')
class WaveformDataWatcherCDB(WaveformDataWatcher):
    """This class serves as a wrapper around the waveform stream data event for the purpose of allowing access to this event easier to obtain from within LabVIEW. Constructing and destructing the object registers and unregisters, respectively, from the event. The set and get properties for which waveform stream specifications to watch also update the event registration. LabVIEW users can register to the event within this class for use in the event structure in LabVIEW."""

    @overload
    def __init__(self, stream_interface: IWaveformStreaming):
        """Initializes a new instance of the WaveformDataWatcherCDB class.

        Args:
            stream_interface: Instance of the interface with which to register the waveform data event
        """

    @overload
    def __init__(self, stream_interface: IWaveformStreaming, waveform_stream_specifications: Sequence[WaveformStreamSpecification]):
        """Initializes a new instance of the WaveformDataWatcherCDB class with the specified waveform stream specifications

        Args:
            stream_interface: Instance of the interface with which to register the waveform data event
            waveform_stream_specifications: Waveform Stream Specifications this watcher returns data for.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    def subscribe_waveform_data_event_handler(self, handler: Callable[[Any, WaveformDataCDBEventArgs], None]) -> None:
        """Event to register a callback to receive notifications when waveform data arrives

        ``handler(sender: Any, e: WaveformDataCDBEventArgs) -> None``

        sender:

        e:
        """
        shim = _subscribe_event_handler(handler, self._dotnet_instance, "WaveformDataEventHandler", System.EventHandler[NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataCDBEventArgs])
        self._dotnet_instance.WaveformDataEventHandler += shim

    def unsubscribe_waveform_data_event_handler(self, handler: Callable[[Any, WaveformDataCDBEventArgs], None]) -> None:
        """Pass the same callable that was given to ``subscribe_waveform_data_event_handler``."""
        shim = _pop_event_handler_from_cache(handler, self._dotnet_instance, "WaveformDataEventHandler")
        if shim is not None:
            self._dotnet_instance.WaveformDataEventHandler -= shim


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataWatcherDBL')
class WaveformDataWatcherDBL(WaveformDataWatcher):
    """This class serves as a wrapper around the waveform stream data event for the purpose of allowing access to this event easier to obtain from within LabVIEW. Constructing and destructing the object registers and unregisters, respectively, from the event. The set and get properties for which waveform stream specifications to watch also update the event registration. LabVIEW users can register to the event within this class for use in the event structure in LabVIEW."""

    @overload
    def __init__(self, stream_interface: IWaveformStreaming):
        """Initializes a new instance of the WaveformDataWatcherDBL class.

        Args:
            stream_interface: Instance of the interface with which to register the waveform data event
        """

    @overload
    def __init__(self, stream_interface: IWaveformStreaming, waveform_stream_specifications: Sequence[WaveformStreamSpecification]):
        """Initializes a new instance of the WaveformDataWatcherDBL class with the specified waveform stream specifications

        Args:
            stream_interface: Instance of the interface with which to register the waveform data event
            waveform_stream_specifications: Waveform Stream Specifications this watcher returns data for.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    def subscribe_waveform_data_event_handler(self, handler: Callable[[Any, WaveformDataDBLEventArgs], None]) -> None:
        """Event to register a callback to receive notifications when waveform data arrives

        ``handler(sender: Any, e: WaveformDataDBLEventArgs) -> None``

        sender:

        e:
        """
        shim = _subscribe_event_handler(handler, self._dotnet_instance, "WaveformDataEventHandler", System.EventHandler[NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataDBLEventArgs])
        self._dotnet_instance.WaveformDataEventHandler += shim

    def unsubscribe_waveform_data_event_handler(self, handler: Callable[[Any, WaveformDataDBLEventArgs], None]) -> None:
        """Pass the same callable that was given to ``subscribe_waveform_data_event_handler``."""
        shim = _pop_event_handler_from_cache(handler, self._dotnet_instance, "WaveformDataEventHandler")
        if shim is not None:
            self._dotnet_instance.WaveformDataEventHandler -= shim


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformStreamCondition', False)
class WaveformStreamCondition(_DotNetBase):
    """Specifies a condition that determines when waveform streaming is active"""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    def get_hash_code(self) -> int:
        """Serves as a hash function for a niveristand.clientapi.waveformstreaming.WaveformStreamCondition object. The hash code this method returns is suitable for use in hashing algorithms and data structures like a hash table.

        Returns:
            int: A hash code for the current niveristand.clientapi.waveformstreaming.WaveformStreamCondition object.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def equals(self, other: WaveformStreamCondition) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.WaveformStreamCondition.

        Args:
            other: The niveristand.clientapi.waveformstreaming.WaveformStreamCondition object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.WaveformStreamCondition. Otherwise, false.
        """
        unwrapped = _unwrap(None, other)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformStreamConditionSerializationBinder')
class WaveformStreamConditionSerializationBinder(_DotNetBase):
    """Provides a custom serialization binder for handling WaveformStreamCondition known types during deserialization."""

    @overload
    def __init__(self):
        """Initializes a new instance of the niveristand.clientapi.waveformstreaming.WaveformStreamConditionSerializationBinder class."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    def bind_to_type(self, assembly_name: str, type_name: str) -> System.Type:
        """Determines the system.Type of the object with the specified type_name.

        Args:
            assembly_name: The name of the assembly to bind the type to.
            type_name: The name of the type to bind.

        Returns:
            System.Type: The system.Type of the object with the specified type_name.
        """
        unwrapped = _unwrap(None, assembly_name, type_name)
        try:
            dotnet_result = self._dotnet_instance.BindToType(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def bind_to_name(self, serialized_type: System.Type) -> Tuple[str, str]:
        """Determines the assembly name and type name for the specified serialized_type.

        Args:
            serialized_type: The system.Type of the object to serialize.

        Returns:
            assembly_name (str): The assembly name of the specified serialized_type.
            type_name (str): The type name of the specified serialized_type.
        """
        unwrapped = _unwrap(None, serialized_type)
        try:
            dotnet_result = self._dotnet_instance.BindToName(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformStreamSpecification')
class WaveformStreamSpecification(_DotNetBase):
    """Specifies properties for a waveform stream."""

    @overload
    def __init__(self, waveform_path: str):
        """Initializes a new instance of the WaveformStreamSpecification class.

        Args:
            waveform_path: The system definition path of the waveform to stream.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def waveform_path(self) -> str:
        """Gets or sets a value indicating the system definition path of the waveform to stream."""
        try:
            dotnet_result = self._dotnet_instance.WaveformPath
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @waveform_path.setter
    def waveform_path(self, value: str):
        """Gets or sets a value indicating the system definition path of the waveform to stream."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.WaveformPath = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def stream_data_at_acquisition_rate(self) -> bool:
        """Gets or sets a value indicating whether the waveform stream data is transferred at the rate at which the target is acquiring the data."""
        try:
            dotnet_result = self._dotnet_instance.StreamDataAtAcquisionRate
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @stream_data_at_acquisition_rate.setter
    def stream_data_at_acquisition_rate(self, value: bool):
        """Gets or sets a value indicating whether the waveform stream data is transferred at the rate at which the target is acquiring the data."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.StreamDataAtAcquisionRate = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def custom_rate(self) -> float:
        """Gets or sets a value indicating the requested rate in Hertz at which data will be streamed. The actual rates at which data is streamed may be coerced to an even divisor of the rates at which the targets in the system definition produce data. This property is ignored unless niveristand.clientapi.waveformstreaming.WaveformStreamSpecification.stream_data_at_acquisition_rate is false."""
        try:
            dotnet_result = self._dotnet_instance.CustomRate
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @custom_rate.setter
    def custom_rate(self, value: float):
        """Gets or sets a value indicating the requested rate in Hertz at which data will be streamed. The actual rates at which data is streamed may be coerced to an even divisor of the rates at which the targets in the system definition produce data. This property is ignored unless niveristand.clientapi.waveformstreaming.WaveformStreamSpecification.stream_data_at_acquisition_rate is false."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.CustomRate = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def stream_condition(self) -> WaveformStreamCondition:
        """Gets or sets a value indicating the condition used to determine when to stream data."""
        try:
            dotnet_result = self._dotnet_instance.StreamCondition
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @stream_condition.setter
    def stream_condition(self, value: WaveformStreamCondition):
        """Gets or sets a value indicating the condition used to determine when to stream data."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.StreamCondition = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @overload
    def equals(self, other: WaveformStreamSpecification) -> bool:
        """Indicates whether the current WaveformStreamSpecification is equivalent to another WaveformStreamSpecification

        Args:
            other: An WaveformStreamSpecification to compare with this WaveformStreamSpecification.

        Returns:
            bool: true if the current WaveformStreamSpecification is equivalent to the other parameter; otherwise, false.
        """

    @overload
    def equals(self, obj: Any) -> bool:
        """Indicates whether the current object is equivalent to another object of the same type

        Args:
            obj: An object to compare with this object.

        Returns:
            bool: true if the current object is equivalent to the other parameter; otherwise, false.
        """

    def equals(self, *args):
        """Indicates whether the current WaveformStreamSpecification is equivalent to another WaveformStreamSpecification"""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Returns the hash code for this WaveformStreamSpecification.

        Returns:
            int: The hash code for this WaveformStreamSpecification.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


    @_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformStreamSpecification.EqualityComparer')
    class EqualityComparer(_DotNetBase):
        """Class that provides the equality comparer for the WaveformStreamSpecification class for use in dictionaries"""

        @overload
        def __init__(self):
            ...

        def __init__(self, *args):
            _init_dotnet_wrapper(self, *args)

        def equals(self, x: WaveformStreamSpecification, y: WaveformStreamSpecification) -> bool:
            """Method that determines if two WaveformStreamSpecification instances are equal

            Args:
                x: left-side operand
                y: right-side operand

            Returns:
                bool: are equal?
            """
            unwrapped = _unwrap(None, x, y)
            try:
                dotnet_result = self._dotnet_instance.Equals(*unwrapped)
            except System.Exception as e:
                _wrap_exception(e)
            return _wrap(dotnet_result)

        def get_hash_code(self, obj: WaveformStreamSpecification) -> int:
            """Overrides GetHashCode method

            Args:
                obj: WaveformStreamSpecification instance to get hash code for

            Returns:
                int: Hashcode of WaveformStreamSpecification
            """
            unwrapped = _unwrap(None, obj)
            try:
                dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
            except System.Exception as e:
                _wrap_exception(e)
            return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.StreamAllData')
class StreamAllData(WaveformStreamCondition):
    """Specifies a stream condition that is always true."""

    @overload
    def __init__(self):
        """Initializes a new instance of the StreamAllData class."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @overload
    def equals(self, other: StreamAllData) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamAllData. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamAllData.

        Args:
            other: The niveristand.clientapi.waveformstreaming.StreamAllData object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance. Otherwise, false.
        """

    @overload
    def equals(self, other: WaveformStreamCondition) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamAllData.

        Args:
            other: The niveristand.clientapi.waveformstreaming.WaveformStreamCondition object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamAllData. Otherwise, false.
        """

    def equals(self, *args):
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamAllData. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamAllData."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Serves as a hash function for a niveristand.clientapi.waveformstreaming.StreamAllData object. The hash code this method returns is suitable for use in hashing algorithms and data structures like a hash table.

        Returns:
            int: A hash code for the current niveristand.clientapi.waveformstreaming.StreamAllData object.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.StreamFirstNSeconds')
class StreamFirstNSeconds(WaveformStreamCondition):
    """Specifies a waveform streaming condition that is true during the first N seconds of waveform data after the waveform starts."""

    @overload
    def __init__(self, n_seconds: float):
        """Initializes a new instance of the StreamFirstNSeconds class.

        Args:
            n_seconds: Length in seconds after the waveform starts that this stream condition is true
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def n_seconds(self) -> float:
        """Gets or sets a value indicating the N seconds after waveform start the condition is true"""
        try:
            dotnet_result = self._dotnet_instance.NSeconds
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @n_seconds.setter
    def n_seconds(self, value: float):
        """Gets or sets a value indicating the N seconds after waveform start the condition is true"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.NSeconds = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @overload
    def equals(self, other: StreamFirstNSeconds) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamFirstNSeconds. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamFirstNSeconds.

        Args:
            other: The niveristand.clientapi.waveformstreaming.StreamFirstNSeconds object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance. Otherwise, false.
        """

    @overload
    def equals(self, other: WaveformStreamCondition) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamFirstNSeconds.

        Args:
            other: The niveristand.clientapi.waveformstreaming.WaveformStreamCondition object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamFirstNSeconds. Otherwise, false.
        """

    def equals(self, *args):
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamFirstNSeconds. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamFirstNSeconds."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Serves as a hash function for a niveristand.clientapi.waveformstreaming.StreamFirstNSeconds object. The hash code this method returns is suitable for use in hashing algorithms and data structures like a hash table.

        Returns:
            int: A hash code for the current niveristand.clientapi.waveformstreaming.StreamFirstNSeconds object.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.StreamInRangeDBL')
class StreamInRangeDBL(WaveformStreamCondition):
    """Specifies a waveform streaming condition for waveforms of Double data type that is true when the data is inside a defined range."""

    @overload
    def __init__(self, high_limit: float, low_limit: float, invert: bool):
        """Initializes a new instance of the StreamInRangeDBL class.

        Args:
            high_limit: Specifies the highest value that the waveform data can be for the stream condition to be true.
            low_limit: Specifies the lowest value that the waveform data can be for the stream condition to be true.
            invert: Specifies if the range check should be inverted. This effectively makes it an out of range condition.
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def high_limit(self) -> float:
        """Gets or sets a value indicating the high limit value of the waveform stream condition."""
        try:
            dotnet_result = self._dotnet_instance.HighLimit
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @high_limit.setter
    def high_limit(self, value: float):
        """Gets or sets a value indicating the high limit value of the waveform stream condition."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.HighLimit = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def low_limit(self) -> float:
        """Gets or sets a value indicating the low limit value of the waveform stream condition."""
        try:
            dotnet_result = self._dotnet_instance.LowLimit
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @low_limit.setter
    def low_limit(self, value: float):
        """Gets or sets a value indicating the low limit value of the waveform stream condition."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.LowLimit = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def invert(self) -> bool:
        """Gets or sets a value indicating whether to invert the range check. If the range check is inverted, then the stream condition occurs when the value falls outside the specified range."""
        try:
            dotnet_result = self._dotnet_instance.Invert
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @invert.setter
    def invert(self, value: bool):
        """Gets or sets a value indicating whether to invert the range check. If the range check is inverted, then the stream condition occurs when the value falls outside the specified range."""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.Invert = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @overload
    def equals(self, other: StreamInRangeDBL) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamInRangeDBL. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamInRangeDBL.

        Args:
            other: The niveristand.clientapi.waveformstreaming.StreamInRangeDBL object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance. Otherwise, false.
        """

    @overload
    def equals(self, other: WaveformStreamCondition) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamInRangeDBL.

        Args:
            other: The niveristand.clientapi.waveformstreaming.WaveformStreamCondition object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamInRangeDBL. Otherwise, false.
        """

    def equals(self, *args):
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamInRangeDBL. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamInRangeDBL."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Serves as a hash function for a niveristand.clientapi.waveformstreaming.StreamInRangeDBL object. The hash code this method returns is suitable for use in hashing algorithms and data structures like a hash table.

        Returns:
            int: A hash code for the current niveristand.clientapi.waveformstreaming.StreamInRangeDBL object.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.StreamNOfMSeconds')
class StreamNOfMSeconds(WaveformStreamCondition):
    """Specifies a waveform streaming condition that is true during the first N seconds of waveform data after the waveform starts and true again for N seconds after M total seconds have elapsed."""

    @overload
    def __init__(self, n_seconds: float, m_seconds: float):
        """Initializes a new instance of the StreamNOfMSeconds class.

        Args:
            n_seconds: Length in seconds after the waveform starts that this stream condition is true
            m_seconds: Length in seconds after the waveform starts to begin repeating the N seconds true duration
        """

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def n_seconds(self) -> float:
        """Gets or sets a value indicating the N seconds after waveform start the condition is true"""
        try:
            dotnet_result = self._dotnet_instance.NSeconds
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @n_seconds.setter
    def n_seconds(self, value: float):
        """Gets or sets a value indicating the N seconds after waveform start the condition is true"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.NSeconds = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @property
    def m_seconds(self) -> float:
        """Gets or sets a value indicating the M seconds after waveform start that the N seconds true duration repeats"""
        try:
            dotnet_result = self._dotnet_instance.MSeconds
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @m_seconds.setter
    def m_seconds(self, value: float):
        """Gets or sets a value indicating the M seconds after waveform start that the N seconds true duration repeats"""
        unwrapped = _unwrap(None, value)
        try:
            self._dotnet_instance.MSeconds = next(unwrapped)
        except System.Exception as e:
            _wrap_exception(e)

    @overload
    def equals(self, other: StreamNOfMSeconds) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamNOfMSeconds. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamNOfMSeconds.

        Args:
            other: The niveristand.clientapi.waveformstreaming.StreamNOfMSeconds object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance. Otherwise, false.
        """

    @overload
    def equals(self, other: WaveformStreamCondition) -> bool:
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamNOfMSeconds.

        Args:
            other: The niveristand.clientapi.waveformstreaming.WaveformStreamCondition object to compare with the current instance.

        Returns:
            bool: true if the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamNOfMSeconds. Otherwise, false.
        """

    def equals(self, *args):
        """Determines whether the specified other object is equal to the current instance of niveristand.clientapi.waveformstreaming.StreamNOfMSeconds. Equivalency is determined using the properties of the niveristand.clientapi.waveformstreaming.StreamNOfMSeconds."""
        unwrapped = _unwrap(None, *args)
        try:
            dotnet_result = self._dotnet_instance.Equals(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    def get_hash_code(self) -> int:
        """Serves as a hash function for a niveristand.clientapi.waveformstreaming.StreamNOfMSeconds object. The hash code this method returns is suitable for use in hashing algorithms and data structures like a hash table.

        Returns:
            int: A hash code for the current niveristand.clientapi.waveformstreaming.StreamNOfMSeconds object.
        """
        unwrapped = _unwrap(None)
        try:
            dotnet_result = self._dotnet_instance.GetHashCode(*unwrapped)
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataCDBEventArgs', False)
class WaveformDataCDBEventArgs(WaveformDataEventArgs):
    """Provides new waveform-stream data for the niveristand.clientapi.waveformstreaming.WaveformDataWatcherCDB.waveform_data_event_handler event."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def real_data(self) -> Sequence[float]:
        """Gets a value indicating the real part of the complex data of the waveform stream."""
        try:
            dotnet_result = self._dotnet_instance.RealData
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)

    @property
    def imaginary_data(self) -> Sequence[float]:
        """Gets a value indicating the imaginary part of the complex data of the waveform stream."""
        try:
            dotnet_result = self._dotnet_instance.ImaginaryData
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)


@_register_dotnet_type('NationalInstruments.VeriStand.ClientAPI.WaveformStreaming.WaveformDataDBLEventArgs', False)
class WaveformDataDBLEventArgs(WaveformDataEventArgs):
    """Provides new waveform-stream data for the niveristand.clientapi.waveformstreaming.WaveformDataWatcherDBL.waveform_data_event_handler event."""

    def __init__(self, *args):
        _init_dotnet_wrapper(self, *args)

    @property
    def data(self) -> Sequence[float]:
        """Gets a value indicating the data of the waveform stream."""
        try:
            dotnet_result = self._dotnet_instance.Data
        except System.Exception as e:
            _wrap_exception(e)
        return _wrap(dotnet_result)
